// --tdd's bounded re-run (#5265): each source bundle that calls a member missing on the one before it
// needs one re-run to be compiled against what the previous pass generated, and the run re-runs at most
// three times. A chain one link past that (app, lib1, lib2, lib3, test: each calls a member the
// previous folder's codeunit lacks) generates a member in the last pass that no pass compiles in. The
// run must say so and must not list that member as generated.
//
// Runner-specific (--tdd's own bound), so it lives here, not in the al-language corpus. The run is
// five bundles over four passes and takes about 40 seconds, so it is the only run of this class.
using Xunit;

namespace AlRunner.Tests;

public sealed class TddRerunLimitRun : TddRunResult
{
    private static readonly string Root = Path.Combine(
        Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..")),
        "AlRunner.Tests", "Fixtures", "TddLibChain");

    public TddRerunLimitRun() : base(
        Path.Combine(Root, "app"), Path.Combine(Root, "lib1"), Path.Combine(Root, "lib2"),
        Path.Combine(Root, "lib3"), Path.Combine(Root, "test")) { }
}

public sealed class TddRerunLimitTests : IClassFixture<TddRerunLimitRun>
{
    private readonly TddRerunLimitRun _run;

    public TddRerunLimitTests(TddRerunLimitRun run) => _run = run;

    private const string Last = "Lib Chain 3: procedure \"M4\"(Arg1: Integer): Integer";

    /// <summary>
    /// The last member of the chain is generated by the pass that hits the limit. It is named by a line
    /// saying the limit stopped it, is left out of the list of generated members, and is named again in
    /// the closing block as not compiled in. The test that needs it fails (it never compiled).
    /// </summary>
    [SkippableFact]
    public void ChainOneLinkPastTheLimit_SaysTheLimitWasReachedAndDoesNotListTheMemberAsGenerated()
    {
        TestArtifacts.SkipIfMissing();

        Assert.Equal(1, _run.Exit);
        Assert.Equal("fail", _run.Find("Reaches").GetProperty("status").GetString());
        Assert.Contains("did not compile", _run.Failure("Reaches"));

        var lines = _run.StdErr.Split('\n').Select(l => l.TrimEnd('\r')).ToList();
        // The three members the three re-runs compiled in are generated; the fourth is not in that list.
        var heading = lines.FindIndex(l => l.Contains(" member(s) this run:", StringComparison.Ordinal));
        Assert.True(heading >= 0, _run.StdErr);
        Assert.Equal("--tdd: generated 3 member(s) this run:", lines[heading]);
        var listed = lines.Skip(heading + 1).TakeWhile(l => l.StartsWith("  Lib Chain ", StringComparison.Ordinal)).ToList();
        Assert.Equal(3, listed.Count);
        Assert.DoesNotContain(listed, l => l.Contains("\"M4\""));

        // The line said when the limit stopped the recompile, and the closing block says it again.
        var limit = Assert.Single(lines, l => l.StartsWith("--tdd: the re-run limit (3) was reached", StringComparison.Ordinal));
        Assert.Contains(Last, limit);
        var closing = lines.FindIndex(l => l.StartsWith("--tdd: 1 more member(s) were generated into another bundle but not compiled in", StringComparison.Ordinal));
        Assert.True(closing > heading, _run.StdErr);
        Assert.Equal($"  {Last}", lines[closing + 1]);
    }
}
