namespace AlRunner;

// Static CLI text: --version, --guide, --help, and `provision --help`. Split out
// of Program.cs (#2665) -- purely static, no captured state.
internal static partial class ProgramSupport
{

    // ── --guide ───────────────────────────────────────────────────────────────────
    // Written for an automated caller that has the binary and nothing else: no repo
    // checkout, no handoff notes, no prior session. It answers, in order, the four
    // questions such a caller gets wrong: what this runner can actually do, how to
    // invoke it against a real app, where dependencies come from, and what the
    // common failure signatures mean. Keep it self-contained — the moment an agent
    // has to go read docs/ or a HANDOFF file to form a correct invocation, this
    // guide has failed at its job.
    // Shared by --version/-v/-V/version and --help's first line, so a build's
    // self-reported version can never drift between the two surfaces (#2072).
    internal static string VersionString()
        => $"al-runner v{AlRunner.Infrastructure.RunnerVersion.Informational(typeof(Program).Assembly)}";

    internal static void PrintGuide(TextWriter w)
    {
        w.WriteLine("al-runner — AGENT GUIDE");
        w.WriteLine("Operating manual for automated callers. For the flag reference, use --help.");
        w.WriteLine();

        w.WriteLine("CAPABILITY — read this before diagnosing any failure");
        w.WriteLine("  al-runner executes complete AL test suites in-process: it compiles AL from");
        w.WriteLine("  source and/or loads precompiled .app packages, applies its BC runtime patches,");
        w.WriteLine("  and runs every [Test] method. It routinely runs suites in the 1,000+ test");
        w.WriteLine("  range (the al-language corpus and large third-party suites) against BC 28.x.");
        w.WriteLine();
        w.WriteLine("  Therefore: if a run does not produce test results, the overwhelmingly likely");
        w.WriteLine("  cause is a BAD INVOCATION or an INCOMPLETE DEPENDENCY SET — not a missing");
        w.WriteLine("  runner capability. Do NOT report \"al-runner cannot run this suite\" unless the");
        w.WriteLine("  limitation is named in docs/limitations.md. A clean compile does NOT prove the");
        w.WriteLine("  dependency set is runnable (see DEPENDENCIES below); it proves only that");
        w.WriteLine("  symbols resolved.");
        w.WriteLine();

        w.WriteLine("INVOCATION — the shortest correct command lines");
        w.WriteLine("  Run one bundle (a dir containing app.json, or any dir below one):");
        w.WriteLine("    al-runner <bundle-dir>");
        w.WriteLine();
        w.WriteLine("  Run an app together with its separate test app — the usual real-world shape.");
        w.WriteLine("  Pass BOTH dirs; they run sequentially and aggregate into one summary. No");
        w.WriteLine("  --package-cache is needed when deps already resolve from each bundle's own");
        w.WriteLine("  .alpackages/ or the BC artifact cache (see DEPENDENCIES below):");
        w.WriteLine("    al-runner MyApp MyApp.Test");
        w.WriteLine();
        w.WriteLine("  Add --package-cache only when a dependency lives somewhere else (a shared");
        w.WriteLine("  symbols folder outside either bundle, a CI-populated cache dir, etc.):");
        w.WriteLine("    al-runner --package-cache <deps-dir> MyApp MyApp.Test");
        w.WriteLine();
        w.WriteLine("  Pin the BC version explicitly whenever the machine has more than one:");
        w.WriteLine("    al-runner --bc-version 28.2 MyApp MyApp.Test");
        w.WriteLine();
        w.WriteLine("  Narrow to one test while debugging (substring match on Codeunit.Method):");
        w.WriteLine("    al-runner --test MyFeature_Posts_Correctly MyApp.Test");
        w.WriteLine();
        w.WriteLine("  Machine-readable outcome for a CI gate or a scripted caller:");
        w.WriteLine("    al-runner --quiet --out results.json MyApp.Test");
        w.WriteLine("    exit 0 = all passed | 1 = a test failed | 2 = could not execute | 3 = could not compile");
        w.WriteLine("    Pass --no-strict-exit to always exit 0 and parse the JSON regardless of outcome.");
        w.WriteLine();
        w.WriteLine("  Some apps require AL preprocessor symbols to compile outside their normal");
        w.WriteLine("  environment (key-vault bypasses, local-dev switches). Check the app's own");
        w.WriteLine("  documentation for these — omitting a required one produces real, correct");
        w.WriteLine("  test failures that look like runner bugs:");
        w.WriteLine("    al-runner --define SOME_LOCAL_DEV MyApp MyApp.Test");
        w.WriteLine();

        w.WriteLine("DEPENDENCIES — where packages come from, and the trap");
        w.WriteLine("  Dependencies declared in app.json are resolved, in order, from:");
        w.WriteLine("    1. every --package-cache DIR you pass (repeatable)");
        w.WriteLine("    2. the bundle's own .alpackages/");
        w.WriteLine("    3. ~/.bcartifacts.cache");
        w.WriteLine("    4. ~/.local/share/al-runner/artifacts   (the BC artifact cache)");
        w.WriteLine();
        w.WriteLine("  THE TRAP: a .app package may carry SYMBOLS ONLY (type/method signatures, no");
        w.WriteLine("  compiled bodies) or it may be CODE-BEARING. The AL compiler needs only symbols,");
        w.WriteLine("  so a symbols-only dependency compiles perfectly cleanly and then fails at");
        w.WriteLine("  RUNTIME the moment its code is called. \"0 compile errors\" is therefore NOT");
        w.WriteLine("  evidence that the dependency set is correct.");
        w.WriteLine();
        w.WriteLine("  HOW THE WINNER IS PICKED — and how NOT to check it. Resolution takes the");
        w.WriteLine("  HIGHEST VERSION of each package across ALL scanned directories combined. So a");
        w.WriteLine("  higher-versioned symbols-only copy outranks the code-bearing one, and the loser");
        w.WriteLine("  is never mentioned anywhere in the output.");
        w.WriteLine();
        w.WriteLine("  CALIBRATION: this happens on healthy configurations too — a test bundle's own");
        w.WriteLine("  .alpackages routinely holds small symbols-only copies that outrank code-bearing");
        w.WriteLine("  ones, on runs that pass completely. So \"a symbols-only package won\" is EVIDENCE");
        w.WriteLine("  TO WEIGH, not a verdict. --verbose lists them as [dep] note: lines. Treat them as");
        w.WriteLine("  the first place to look when execution fails, not as proof of the cause.");
        w.WriteLine();
        w.WriteLine("    Do NOT conclude \"shadowing is ruled out\" by hashing or swapping the ONE");
        w.WriteLine("    package named in the error. The package that failed is usually not the");
        w.WriteLine("    package that was shadowed — a test library dies because something it depends");
        w.WriteLine("    on resolved to a symbols-only copy. Checking one file proves nothing about");
        w.WriteLine("    the other hundred.");
        w.WriteLine();
        w.WriteLine("    Instead, make it mechanical — re-run with --verbose and read the [dep] lines:");
        w.WriteLine("      [dep] <Publisher>/<Name> <Version>  <- /path/to/the/winning.app");
        w.WriteLine("    That is the resolved set. Check the path and version of each dependency that");
        w.WriteLine("    is actually on the failing call's path, not just the one that threw.");
        w.WriteLine();
        w.WriteLine("    The [dep] winner comes FROM somewhere: --verbose also lists every directory");
        w.WriteLine("    actually searched to produce it, as [pkg-cache] lines under the \"package");
        w.WriteLine("    caches (final search set): N dir(s)\" count — not the earlier \"(requested)\"");
        w.WriteLine("    count, which is the explicit/default set only. If a package you expect to");
        w.WriteLine("    win is missing, check whether its directory is even in the final list.");
        w.WriteLine();
        w.WriteLine("  VERSION SKEW ACROSS A FAMILY. When a workspace's .alpackages reference two");
        w.WriteLine("  different minors of the same platform family, stage BOTH minors in the");
        w.WriteLine("  dependency directory. Supplying only the higher one lets a symbols-only copy");
        w.WriteLine("  win over the code-bearing package the app actually needs at runtime. Test");
        w.WriteLine("  toolkit libraries and platform apps are frequently on DIFFERENT minors than");
        w.WriteLine("  the app under test — that is normal and must be preserved, not normalised.");
        w.WriteLine();
        w.WriteLine("  WHICH BC VERSION TO PASS. Do NOT infer it from the app under test. The runner");
        w.WriteLine("  selects within the major its ENGINE was built against, and one engine build");
        w.WriteLine("  spans the minors of that major — a 28.1-built engine runs 28.2 business logic");
        w.WriteLine("  correctly. So the right --bc-version is the one whose service-tier artifacts");
        w.WriteLine("  are present for this engine, which is NOT necessarily the version stamped on");
        w.WriteLine("  the app's dependencies. `--bc-version 28.1` while the app references 28.2");
        w.WriteLine("  packages is a normal, working configuration, not a mismatch to \"fix\".");
        w.WriteLine("  Attributing a runtime failure to \"the engine's BC-X.Y patch set\" without");
        w.WriteLine("  knowing which version was actually selected is a guess. The runner PRINTS its");
        w.WriteLine("  selection at the start of every run — look for the \"[bc] no --bc-version");
        w.WriteLine("  given — selecting/provisioning BC ...\" and \"[bc] selected BC ... (path)\" lines");
        w.WriteLine("  on stderr — so read those rather than assuming which default applied. Pin");
        w.WriteLine("  --bc-version explicitly anyway on a machine with more than one cached BC");
        w.WriteLine("  version, so a run's outcome does not depend on which default logic fires.");
        w.WriteLine();
        w.WriteLine("  BC artifacts are provisioned AUTOMATICALLY by default (issue #2024): a first run");
        w.WriteLine("  against an empty ~/.local/share/al-runner/artifacts downloads the engine +");
        w.WriteLine("  platform/test apps it needs and continues, no flag required. Pass");
        w.WriteLine("  --no-auto-provision to refuse network access (offline/air-gapped machines) —");
        w.WriteLine("  a refused or failed provision still fails loud, naming exactly what is");
        w.WriteLine("  missing and a fix command that is valid for a `dotnet tool install`, never a");
        w.WriteLine("  silent stub. Other provisioning entry points:");
        w.WriteLine("    al-runner provision <bundle-dir>        # provision for that project's version, then exit");
        w.WriteLine("    al-runner --auto-provision <dirs>       # same as the default, explicit for scripts");
        w.WriteLine("    al-runner --no-auto-provision <dirs>    # fail loud instead of reaching the network");
        w.WriteLine();
        w.WriteLine("  Auto-provisioning only ever fetches the w1 (worldwide) artifact by default. A");
        w.WriteLine("  project depending on a country-localization Microsoft app (e.g. \"IRS Forms\") can");
        w.WriteLine("  NEVER be satisfied that way, no matter how many times `provision`/");
        w.WriteLine("  --auto-provision is re-run — the \"Missing: Microsoft/...\" message says so and");
        w.WriteLine("  names --country as the fix when that looks like the cause:");
        w.WriteLine("    al-runner --auto-provision --country us <bundle-dir>");
        w.WriteLine("  A country set is provisioned into its own \"platform-apps-<code>\" cache directory,");
        w.WriteLine("  separate from w1's, so provisioning both leaves both usable.");
        w.WriteLine();
        w.WriteLine("  DEMO / TEST DATA (issue #2258). By default the database starts EMPTY: install");
        w.WriteLine("  triggers and Company-Initialize seed it, and nothing else does. AL that expects a");
        w.WriteLine("  real environment's setup records (No. Series, posting groups, Source Code Setup)");
        w.WriteLine("  therefore fails with \"... must have a value in ...\" — that is missing data, not a");
        w.WriteLine("  bug in your test. Pass --test-data to load those rows from the BC backup shipped");
        w.WriteLine("  inside the artifact. A table is read the first time the run touches it, so the");
        w.WriteLine("  cost tracks what the suite actually uses:");
        w.WriteLine("    al-runner --test-data <bundle-dir>              # the shipped backup for the selected version/country");
        w.WriteLine("    al-runner --test-data=/path/to/X.bak <dirs>     # an explicit backup");
        w.WriteLine("    al-runner --test-data --test-data-company NAME  # a specific company inside it");
        w.WriteLine("  You do not have to know in advance which failures those are: when a test fails on a");
        w.WriteLine("  table that has NO rows in this run, the runner prints a one-line [test-data] note");
        w.WriteLine("  under the failure naming that table. BC's own message is left exactly as it was —");
        w.WriteLine("  the note sits next to it. It only appears when the failure names a table AND that");
        w.WriteLine("  table is measurably empty, so a real bug against a populated table is never");
        w.WriteLine("  mislabelled. With --test-data already on it says instead why the table is still");
        w.WriteLine("  empty (refused, not in this backup, or empty in it).");
        w.WriteLine("  It needs the `bcbak` backup reader on PATH or at $AL_RUNNER_BCBAK. Each table is");
        w.WriteLine("  read once per process, at first touch, and then lives in the install baseline");
        w.WriteLine("  the runner restores at every test boundary. A missing backup FAILS the run");
        w.WriteLine("  naming every path probed —");
        w.WriteLine("  it never continues against an empty database. Table-extension fields and");
        w.WriteLine("  Date/DateTime/Time/DateFormula values are rebuilt; BLOB/media values are NOT yet,");
        w.WriteLine("  and a table carrying one is refused whole. Every skipped or refused table is named on");
        w.WriteLine("  stderr with the reason. See docs/limitations.md.");
        w.WriteLine("  If a provisioning-gap message names a specific missing set, force just that one");
        w.WriteLine("  (bypasses need-detection entirely — useful when the default `provision` mis-detects,");
        w.WriteLine("  issue #2085):");
        w.WriteLine("    al-runner provision --platform-apps --bc-version V [--force]");
        w.WriteLine("    al-runner provision --test-apps --bc-version V [--force]");
        w.WriteLine("    al-runner provision --service-tier --bc-version V [--force]");
        w.WriteLine("  Every one of these works from a plain `dotnet tool install -g` with no source");
        w.WriteLine("  checkout — the standalone tools/DownloadArtifacts project these wrap ships only");
        w.WriteLine("  as source in this repo and is unreachable from an installed tool.");
        w.WriteLine("  The engine must be built against the same BC MINOR as the target artifacts");
        w.WriteLine("  (28.1 vs 28.2 matters; a major-only match is not sufficient).");
        w.WriteLine();

        w.WriteLine("PRE-FLIGHT — do these before concluding anything about a failure");
        w.WriteLine("  1. al-runner --version");
        w.WriteLine("  2. Confirm the artifact version you are running against resolves as intended —");
        w.WriteLine("     read the \"[bc] selected BC ...\" line the runner always prints, rather than");
        w.WriteLine("     assuming which default logic fired (see EXECUTION's --bc-version entry).");
        w.WriteLine("  3. Re-run the failing case alone with --test <name> --verbose. --verbose turns");
        w.WriteLine("     on the internal [Component] logs that name the failing subsystem.");
        w.WriteLine("  4. Re-run with --no-cache once. Compiled output is cached by default, and a few");
        w.WriteLine("     defect classes only appear on a cache HIT (or only on a MISS).");
        w.WriteLine();

        w.WriteLine("TROUBLESHOOTING — failure signature, meaning, action");
        w.WriteLine();
        w.WriteLine("  \"NavNCLMissingMethodException: Function ID <n> was called. The object with");
        w.WriteLine("   ID 0 does not have a member with that ID.\"");
        w.WriteLine("      Meaning: the call resolved against a module whose AL objects have no IDs —");
        w.WriteLine("      i.e. a symbols-only package won over a code-bearing one, or a module's");
        w.WriteLine("      emit did not complete. Object ID 0 is the tell. This is a RESOLUTION");
        w.WriteLine("      failure. It does NOT mean the runner is missing a native/platform method:");
        w.WriteLine("      the named function is ordinary AL in some dependency, and the runner");
        w.WriteLine("      failed to find the code for it — it is not an unimplemented intrinsic.");
        w.WriteLine("      Action: re-run with --verbose and read the [dep] lines to see which .app");
        w.WriteLine("      won for every dependency on the failing path (see DEPENDENCIES above);");
        w.WriteLine("      stage every minor the workspace references; re-run with --no-cache. This");
        w.WriteLine("      is a dependency/invocation problem far more often than a runner gap.");
        w.WriteLine();
        w.WriteLine("  Failure inside an install trigger (OnInstallAppPerCompany/PerDatabase)");
        w.WriteLine("      Install triggers are implemented and do run — a large suite exercising the");
        w.WriteLine("      MS test toolkit fires them on every run. A failure here is therefore about");
        w.WriteLine("      the dependency set you supplied, not about trigger support being absent.");
        w.WriteLine("      Apply the ID-0 checklist above.");
        w.WriteLine();
        w.WriteLine("  \"RunnerOutOfScopeException: <api> — <reason>\"");
        w.WriteLine("      Meaning: WORKING AS INTENDED. The test touched a surface the runner");
        w.WriteLine("      deliberately does not emulate (SMTP, outbound HTTP, printing, external");
        w.WriteLine("      file I/O, web-service publishing). The runner throws loudly rather than");
        w.WriteLine("      returning a fake value that would make a green test lie.");
        w.WriteLine("      Action: see docs/scope.md. This is not a bug and not a gap.");
        w.WriteLine();
        w.WriteLine("  Could not resolve dependency / unresolved symbol at compile time");
        w.WriteLine("      Action: add the missing .app's directory via --package-cache.");
        w.WriteLine();
        w.WriteLine("  Artifact version not found");
        w.WriteLine("      Action: auto-provisioning is on by default and should have fetched it —");
        w.WriteLine("      if you passed --no-auto-provision, drop it (or run `al-runner provision`");
        w.WriteLine("      explicitly). If provisioning itself failed (no network), point");
        w.WriteLine("      --artifact-path at an existing artifact root instead.");
        w.WriteLine();
        w.WriteLine("  Compile succeeds, tests still do not run");
        w.WriteLine("      Action: read the DEPENDENCIES trap above. Compilation validates symbols");
        w.WriteLine("      only; it says nothing about whether the code is present to execute.");
        w.WriteLine();

        w.WriteLine("OUTPUT NOTES");
        w.WriteLine("  Console output written from inside a test is captured by the runner, not");
        w.WriteLine("  echoed live — a probe that writes to stdout will appear to produce nothing.");
        w.WriteLine("  Write diagnostics to a FILE instead.");
        w.WriteLine("  In --server mode stdout carries ONLY the JSON protocol; all logs go to stderr.");
        w.WriteLine("  Same for --dap stdio: stdout carries ONLY the DAP wire format, all logs go to");
        w.WriteLine("  stderr. --dap [PORT] (TCP) is unaffected — stdout is normal there.");
        w.WriteLine();

        w.WriteLine("TDD MODE (--tdd) — starting a red-green cycle before the app has the symbol yet");
        w.WriteLine("  Local development only. Not for CI: it deliberately runs tests that reference");
        w.WriteLine("  symbols the implementing app doesn't have yet, instead of failing the compile.");
        w.WriteLine();
        w.WriteLine("  Normally, a test written before its implementation is a compile error —");
        w.WriteLine("  method-body errors drop the WHOLE app group (BC's continue-on-error does not");
        w.WriteLine("  cover them), so the run reports exit 3 and zero test results, not a red test.");
        w.WriteLine("  --tdd infers the missing member's type from how the test uses it (a field's");
        w.WriteLine("  type from what's assigned to it, a procedure's parameter/return types from its");
        w.WriteLine("  call site), generates it into the implementing app's source in memory, and");
        w.WriteLine("  recompiles. The generated body raises a distinctive error naming itself as a");
        w.WriteLine("  generated stub, so the test runs up to that point and fails there — a genuine");
        w.WriteLine("  RED test, for the reason you intended, instead of a compile failure:");
        w.WriteLine("    al-runner --tdd MyApp MyApp.Test");
        w.WriteLine();
        w.WriteLine("  Where nothing anchors a confident guess (a bare-statement call — no way to");
        w.WriteLine("  tell a void procedure from a discarded return value — or both sides of an");
        w.WriteLine("  assignment unresolved), --tdd REFUSES rather than invents: that test is still");
        w.WriteLine("  reported FAILED, naming the missing symbol, exactly as before generation");
        w.WriteLine("  existed. A wrong guess that compiled cleanly would be worse than no guess —");
        w.WriteLine("  a test red for the wrong reason. At the end of the run, --tdd prints every");
        w.WriteLine("  member it actually generated: that list is the API surface the implementing");
        w.WriteLine("  app still has to hand-write to replace the stubs.");
        w.WriteLine();
        w.WriteLine("  Exit code is 1 (a test failed), not 3 (compile failed) — --tdd's whole point");
        w.WriteLine("  is turning that 3 into a 1 you can iterate against.");
        w.WriteLine();
        w.WriteLine("  --tdd disables the AL-output cache for the run (its generated members and");
        w.WriteLine("  synthetic results are derived fresh from source every time; a cache HIT would");
        w.WriteLine("  silently skip generation and serve stale or missing results).");
        w.WriteLine();
        w.WriteLine("  --tdd + --watch is REJECTED (exit 2), not silently combined. --watch's whole");
        w.WriteLine("  premise is a stable, unchanging source tree it can diff between cycles — a");
        w.WriteLine("  --tdd run mutates the app's own in-memory source every cycle by design, so");
        w.WriteLine("  the two are fundamentally incompatible rather than merely untested together.");
        w.WriteLine("  --tdd + --server is rejected the same way.");
        w.WriteLine();
        w.WriteLine("  Scope: source-compiled implementing apps only. A precompiled .app dependency's");
        w.WriteLine("  missing member is not generated — precompiled-dll-respect.md forbids rewriting");
        w.WriteLine("  compiled bodies, and that diagnostic falls through to the same refuse path.");
        w.WriteLine();

        w.WriteLine("REPORTING A RUNNER GAP");
        w.WriteLine("  Only after PRE-FLIGHT and TROUBLESHOOTING have been worked through, and the");
        w.WriteLine("  behaviour is not described in docs/limitations.md or docs/scope.md. A gap");
        w.WriteLine("  report needs a minimal runnable AL reproducer and the exact failing assertion");
        w.WriteLine("  or diagnostic. Do not guess at a cause, and do not silently work around it.");
        w.WriteLine();
        w.WriteLine("  Before filing, you must be able to answer all of:");
        w.WriteLine("    - Which BC version did the run actually select? (--verbose)");
        w.WriteLine("    - What is the full resolved dependency set, with winning paths? ([dep] lines)");
        w.WriteLine("    - Does it still fail with --no-cache?");
        w.WriteLine("    - Is the mechanism you are naming consistent with the error? (\"unimplemented");
        w.WriteLine("      native method\" does not explain an object-ID-0 resolution failure.)");
        w.WriteLine("  A report that names a cause the evidence does not support is worse than none:");
        w.WriteLine("  it sends someone to fix a subsystem that was never involved.");
        w.WriteLine();
        w.WriteLine("  Where to file: https://github.com/StefanMaron/BusinessCentral.AL.Runner/issues");
        w.WriteLine("  Gap reports are welcome — this is the replacement for the telemetry channel");
        w.WriteLine("  that used to exist (#1643, closed not-planned); nothing is sent anywhere");
        w.WriteLine("  automatically, and no report happens without a human reading it first.");
        w.WriteLine();
        w.WriteLine("  Before posting anything: ask the person you are working with for permission,");
        w.WriteLine("  and show them the report text first. Do not open the issue on your own, and");
        w.WriteLine("  do not silently work around the gap instead — both are wrong. Filing without");
        w.WriteLine("  asking treats someone else's repository as yours to post to; working around it");
        w.WriteLine("  silently is exactly what runner-gap tracking exists to prevent.");
        w.WriteLine();
        w.WriteLine("  An uncertain report is still worth offering, as long as the uncertainty is");
        w.WriteLine("  stated plainly. \"I do not know what caused this, here is the reproducer\" is a");
        w.WriteLine("  good report. \"This is a metadata cache bug\", offered with no evidence for");
        w.WriteLine("  that specific mechanism, is not — that is the cause-without-support problem");
        w.WriteLine("  above, just stated with more confidence than the evidence supports.");
        w.WriteLine();

        w.WriteLine("FURTHER READING");
        w.WriteLine("  --help                       full flag reference");
        w.WriteLine("  docs/limitations.md          the real architectural limits");
        w.WriteLine("  docs/scope.md                in-scope vs out-of-scope-by-design surfaces");
        w.WriteLine("  docs/server-mode.md          the --server JSON-RPC protocol");
        w.WriteLine("  docs/dap-mode.md             the --dap Debug Adapter Protocol server");
    }

    internal static void PrintHelp(TextWriter w)
    {
        // First line so a build carries its own version wherever --help output gets
        // pasted (e.g. into a gap report) without asking separately for --version's
        // output too (#2072).
        w.WriteLine(VersionString());
        w.WriteLine("al-runner — run Business Central AL unit tests in-process.");
        w.WriteLine();
        w.WriteLine("USAGE");
        w.WriteLine("  al-runner [OPTIONS] <bundle-dir>...");
        w.WriteLine("  al-runner provision [<bundle-dir>]");
        w.WriteLine("  al-runner --server [--package-cache PATH ...] [--cache DIR]");
        w.WriteLine("  al-runner --dap [PORT|stdio] <bundle-dir>");
        w.WriteLine("  al-runner --precompile <input.app> --out <output.dll> [--package-cache PATH ...]");
        w.WriteLine("  al-runner --emit-app <bundleDir> <outPath> [--package-cache PATH ...]");
        w.WriteLine("  al-runner --guide      (operating manual for automated callers)");
        w.WriteLine("  al-runner --version   (also: -v, -V, version)");
        w.WriteLine("  al-runner --help");
        w.WriteLine();
        w.WriteLine("Agents and scripted callers should start with --guide: it covers correct");
        w.WriteLine("invocation against a real app + test app, where dependencies are resolved from,");
        w.WriteLine("and what the common runtime failure signatures actually mean.");
        w.WriteLine();
        w.WriteLine("A <bundle-dir> is a folder that either contains an app.json (a single AL");
        w.WriteLine("package) or sits below one — the bucket root is auto-detected by climbing the");
        w.WriteLine("path. Dependencies declared in app.json are resolved against --package-cache");
        w.WriteLine("dirs, the al-runner artifact cache, and the dotnet tool store.");
        w.WriteLine();
        w.WriteLine("Multiple <bundle-dir> arguments run sequentially and aggregate into one");
        w.WriteLine("summary. Pass --out PATH to also emit a failure-classification JSON.");
        w.WriteLine("Arguments that name the same directory run ONCE: they are de-duplicated by");
        w.WriteLine("resolved real path, so `x`, `./x`, `x/` and a symlink to `x` collapse onto one");
        w.WriteLine("another and the run says which argument it dropped. Two different directories");
        w.WriteLine("are never merged, even when they declare the same app id.");
        w.WriteLine();
        w.WriteLine("SELECTION");
        w.WriteLine("  --test PATTERN, --filter PATTERN");
        w.WriteLine("                          Run only tests whose qualified name (CodeunitNNNN.Method)");
        w.WriteLine("                          contains PATTERN (case-insensitive). Leading/trailing '*'");
        w.WriteLine("                          is accepted as a shell-friendly no-op.");
        w.WriteLine("  --isolation MODE, --test-isolation MODE");
        w.WriteLine("                          Test isolation:");
        w.WriteLine("                            codeunit  state shared inside a codeunit, reset between");
        w.WriteLine("                                      codeunits (default; AL TestIsolation = Codeunit,");
        w.WriteLine("                                      BC's \"Isol. Codeunit\" 130450)");
        w.WriteLine("                            test      every [Test] gets a fresh state");
        w.WriteLine("                                      (AL TestIsolation = Function)");
        w.WriteLine("                            disabled  no resets at all (AL TestIsolation = Disabled,");
        w.WriteLine("                                      BC's \"Isol. Disabled\" 130451)");
        w.WriteLine("                            method    v1 alias for 'test' (v1's per-method reset)");
        w.WriteLine("  --test-timeout SECONDS  Per-test timeout override (v1 carryover). Default: 60s, or");
        w.WriteLine("                          the AL_RUNNER_TEST_TIMEOUT_SEC env var if set; this flag");
        w.WriteLine("                          takes precedence over both. On timeout the test fails with");
        w.WriteLine("                          \"Test exceeded {N}s timeout.\" (v1-compatible message text).");
        w.WriteLine();
        w.WriteLine("EXECUTION");
        w.WriteLine("  --jobs N, -j N          Run the given bundle dirs across N worker PROCESSES and");
        w.WriteLine("                          print one aggregate summary. Bundles are balanced by AL");
        w.WriteLine("                          file count, so one large bundle does not leave the other");
        w.WriteLine("                          workers idle. Exit code is the worst any worker returned.");
        w.WriteLine("                          Sharding also bounds MEMORY. Peak RSS is driven by how many");
        w.WriteLine("                          BUNDLES a process loads, not how many tests it runs:");
        w.WriteLine("                          measured on Microsoft's BaseApp buckets, 3 bundles/939 tests");
        w.WriteLine("                          peaked at 4.4 GB while 1 bundle/1027 tests peaked at 3.7 GB,");
        w.WriteLine("                          and 10x the tests inside ONE bundle cost only +0.4 GB. Many");
        w.WriteLine("                          bundles therefore do not fit in one process, and splitting");
        w.WriteLine("                          them across workers is what makes the run possible at all.");
        w.WriteLine("                          A hung test also ends only its own shard, not the whole run.");
        w.WriteLine("                          Ignored by --watch/--server/--dap (long-lived warm state)");
        w.WriteLine("                          and by a single-bundle run. Default: 1.");
        w.WriteLine("  --resume-aborts N       How many times a run may re-run itself in a fresh process");
        w.WriteLine("                          after a watchdog abort, each time excluding the codeunit");
        w.WriteLine("                          that hung. Default 5; 0 disables. A hung test abandons the");
        w.WriteLine("                          rest of its bundle and cannot be continued in-process (the");
        w.WriteLine("                          hung thread is never killed and keeps mutating shared");
        w.WriteLine("                          state), so a fresh process is the only safe way on. Each");
        w.WriteLine("                          retry re-runs the bundle from the start, so its totals");
        w.WriteLine("                          REPLACE the previous attempt\'s; tests inside an excluded");
        w.WriteLine("                          codeunit are not counted. Measured on Microsoft Tests-ERM:");
        w.WriteLine("                          2 tests ran before, 1066 after one exclusion, 2145 after two.");
        w.WriteLine("  --exclude-test PATTERN  Skip tests matching PATTERN; repeatable. PATTERN is a whole");
        w.WriteLine("                          codeunit name (Codeunit134228) or a whole qualified test");
        w.WriteLine("                          name (Codeunit134228.CloseIncomeStatementTwice) — never a");
        w.WriteLine("                          partial one, so Codeunit1342 cannot silently swallow");
        w.WriteLine("                          Codeunit134228. Exists because a test whose watchdog fires");
        w.WriteLine("                          aborts the rest of its codeunit AND every later codeunit in");
        w.WriteLine("                          the bundle: the hung thread is never killed and keeps");
        w.WriteLine("                          mutating shared state, so continuing in-process would report");
        w.WriteLine("                          results that lie. Re-running with the hung test excluded is");
        w.WriteLine("                          how the abandoned tests get reached.");
        w.WriteLine("  --bc-version X          Select the BC artifact version (e.g. \"28.1\" or a full");
        w.WriteLine("                          version). Default depends on how this binary was");
        w.WriteLine("                          installed: a single-build install (built from source)");
        w.WriteLine("                          targets the exact BC build its engine was compiled");
        w.WriteLine("                          against, falling back to the same major/minor's latest");
        w.WriteLine("                          cached build (with a warning) when that exact build");
        w.WriteLine("                          isn't cached or provisionable. A multi-variant install");
        w.WriteLine("                          (the published tool, which ships several BC minors)");
        w.WriteLine("                          instead defaults to the latest version present in");
        w.WriteLine("                          ~/.local/share/al-runner/artifacts, auto-matching the");
        w.WriteLine("                          shipped engine variant to it. Either way the runner");
        w.WriteLine("                          PRINTS its selection at the start of every run (see the");
        w.WriteLine("                          \"[bc] selected BC ...\" line) — read that instead of");
        w.WriteLine("                          assuming which default applies. A prefix matches the");
        w.WriteLine("                          highest version with that prefix. Missing artifacts are");
        w.WriteLine("                          auto-provisioned by default (see --no-auto-provision);");
        w.WriteLine("                          an unavailable/refused version still fails loud.");
        w.WriteLine("                          Mutually exclusive with --artifact-path.");
        w.WriteLine("  --artifact-path DIR     Use an explicit BC artifact root (the dir containing");
        w.WriteLine("                          platform/ + w1/), bypassing the cache scan. Its version");
        w.WriteLine("                          is read from the dir name or the contained Ncl.dll.");
        w.WriteLine("                          Mutually exclusive with --bc-version.");
        w.WriteLine("  --country CODE          BC artifact country/localization channel to provision from");
        w.WriteLine("                          — \"w1\" (worldwide, default) or a country code such as");
        w.WriteLine("                          \"us\"/\"de\"/\"gb\". A project depending on a country-");
        w.WriteLine("                          localization Microsoft app (e.g. \"IRS Forms\") cannot be");
        w.WriteLine("                          provisioned from w1 at all — the \"Missing: Microsoft/...\"");
        w.WriteLine("                          message names this flag when that is the likely cause.");
        w.WriteLine("                          Not validated against a hardcoded list of codes: an");
        w.WriteLine("                          unresolvable one fails loud, naming the exact CDN URL that");
        w.WriteLine("                          404'd. Provisioned country sets live in their own");
        w.WriteLine("                          \"platform-apps-<code>\" cache directory, separate from the");
        w.WriteLine("                          w1 \"platform-apps\" one, so provisioning both leaves both");
        w.WriteLine("                          usable.");
        w.WriteLine("  --test-data             Hydrate the in-memory database from the BC backup shipped");
        w.WriteLine("                          in the artifact cache, so tests find the setup records a");
        w.WriteLine("                          real environment has. Each table is read the first time");
        w.WriteLine("                          the run touches it, never up front. OFF");
        w.WriteLine("                          BY DEFAULT; absent the flag no backup is opened and");
        w.WriteLine("                          nothing about the run changes. Resolves");
        w.WriteLine("                          sandbox/<version>/<country>/BusinessCentral-<CC>.bak for");
        w.WriteLine("                          the selected BC version and --country; when that is");
        w.WriteLine("                          missing the run FAILS naming every path it probed,");
        w.WriteLine("                          rather than continuing against an empty database.");
        w.WriteLine("                          Needs the `bcbak` backup reader on PATH or at");
        w.WriteLine("                          $AL_RUNNER_BCBAK. A table is read once per process, at");
        w.WriteLine("                          first touch, and then lives in the install baseline the");
        w.WriteLine("                          runner restores at every test boundary.");
        w.WriteLine("                          Table-extension fields and Date/DateTime/Time/DateFormula");
        w.WriteLine("                          values are rebuilt. Tables carrying a BLOB or media value");
        w.WriteLine("                          are still refused whole;");
        w.WriteLine("                          every skipped or refused table is reported with its");
        w.WriteLine("                          reason, never silently dropped.");
        w.WriteLine("  --test-data=PATH        As --test-data, but from an explicit .bak file.");
        w.WriteLine("  --test-data-company NAME");
        w.WriteLine("                          Company inside the backup to hydrate. Default: the first");
        w.WriteLine("                          company the backup reports, which is printed at the start");
        w.WriteLine("                          of the run.");
        w.WriteLine("  --auto-provision        Download the BC artifacts for the project's version if");
        w.WriteLine("                          they are missing, then continue the run. ON BY DEFAULT");
        w.WriteLine("                          since issue #2024 — this flag is now redundant with a");
        w.WriteLine("                          plain run, kept for explicit scripts and back-compat. See");
        w.WriteLine("                          --no-auto-provision to turn it off (or the `provision`");
        w.WriteLine("                          subcommand to provision without running tests).");
        w.WriteLine("  --no-auto-provision     Disable automatic provisioning: a missing/incomplete BC");
        w.WriteLine("                          artifact fails loud instead of downloading it. Use this");
        w.WriteLine("                          on offline/air-gapped machines, or anywhere reaching the");
        w.WriteLine("                          network unasked for gigabyte-scale artifacts is unwanted.");
        w.WriteLine("  --package-cache PATH    Extra directory to scan for .app dependencies");
        w.WriteLine("                          (repeatable). Default scan: ~/.bcartifacts.cache,");
        w.WriteLine("                          ~/.local/share/al-runner/artifacts, and bundle .alpackages/.");
        w.WriteLine("  --cache DIR             Isolation root for every on-disk cache the runner uses:");
        w.WriteLine("                          the AL-output cache (default ~/.cache/al-runner/al-out,");
        w.WriteLine("                          compiled test DLLs re-used on subsequent runs if inputs");
        w.WriteLine("                          are unchanged) AND every other named cache normally under");
        w.WriteLine("                          ~/.cache/al-runner/<name> (compiled-deps, workspace-deps,");
        w.WriteLine("                          ncl-cecil, bc-symbols, and more) as <DIR>/<name>.");
        w.WriteLine("  --no-cache              Disable every on-disk cache for this run, not just the");
        w.WriteLine("                          AL-output cache: the other named caches above are");
        w.WriteLine("                          redirected to a throwaway per-run directory (removed on");
        w.WriteLine("                          exit) instead of the real, shared ~/.cache/al-runner tree,");
        w.WriteLine("                          so a run reached for to reproduce/measure a cold compile");
        w.WriteLine("                          does not silently reuse them. --cache/--no-cache are");
        w.WriteLine("                          last-wins against each other on the command line.");
        w.WriteLine("  --print-cache-key       Diagnostic/test-support mode: compute the AL-output cache");
        w.WriteLine("                          key for the first app group of the first bundle exactly as");
        w.WriteLine("                          a real run would, print \"[cache] KEY key=<hash>\", and exit");
        w.WriteLine("                          without emitting or compiling that app group. NOT free: the");
        w.WriteLine("                          layered dependency pre-pass has already built every");
        w.WriteLine("                          dependency bundle from source by then, and it cannot be");
        w.WriteLine("                          skipped, because the key covers the resolved dependency set.");
        w.WriteLine("                          Requires the cache to be enabled (default; not --no-cache).");
        w.WriteLine("                          Exit code 2 if no key could be computed.");
        w.WriteLine("  --watch                 Stay resident with warm dependencies and re-run IN-PROCESS");
        w.WriteLine("                          on every .al change (deps loaded once → ~seconds/save, not");
        w.WriteLine("                          a cold re-run). Ctrl+C to quit.");
        w.WriteLine("  --server                Long-running JSON-RPC daemon over stdin/stdout (warm");
        w.WriteLine("                          deps + BC patches loaded once; ~19s->~4s per run). One");
        w.WriteLine("                          JSON request/response per line. stdout carries ONLY the");
        w.WriteLine("                          protocol; all logs go to stderr. Used by the VS Code");
        w.WriteLine("                          extension. Commands: runTests (streaming per-test results),");
        w.WriteLine("                          execute (compile+run inline AL source; one response with");
        w.WriteLine("                          tests, Message() output, coverage and captured values),");
        w.WriteLine("                          shutdown. Full wire schema: docs/server-mode.md. Mutually");
        w.WriteLine("                          exclusive with --watch.");
        w.WriteLine("  --dap [PORT]            Debug Adapter Protocol server (default port 4711):");
        w.WriteLine("                          set AL breakpoints, pause execution, inspect locals over a");
        w.WriteLine("                          real DAP TCP connection. Requires exactly one bundle path.");
        w.WriteLine("                          Compiles on `launch`, pauses AL execution at StmtHit for");
        w.WriteLine("                          any breakpointed statement once `configurationDone` starts");
        w.WriteLine("                          the run. next/stepIn/stepOut pause at a real qualifying");
        w.WriteLine("                          statement (step-over/into/out of the current call), not");
        w.WriteLine("                          just at the next breakpoint. See docs/dap-mode.md.");
        w.WriteLine("                          Mutually exclusive with --server.");
        w.WriteLine("  --dap stdio             Same DAP session, over this process's own stdin/stdout");
        w.WriteLine("                          instead of a TCP socket — for a client that launches");
        w.WriteLine("                          al-runner directly (e.g. VS Code's DebugAdapterExecutable),");
        w.WriteLine("                          no port to pick, no readiness race. stdout carries ONLY the");
        w.WriteLine("                          DAP protocol; all logs go to stderr. See docs/dap-mode.md.");
        w.WriteLine("  --tdd                   Local-development flag (not for CI). A test referencing a");
        w.WriteLine("                          table field / procedure / enum value the implementing app");
        w.WriteLine("                          doesn't have yet normally drops the whole app group with a");
        w.WriteLine("                          compile failure (exit 3, zero test results). --tdd keeps");
        w.WriteLine("                          every object that DID compile and reports each [Test]");
        w.WriteLine("                          procedure in an object that could NOT be recovered as a");
        w.WriteLine("                          FAILED test naming the missing symbol, so a red-green TDD");
        w.WriteLine("                          cycle can start with an honestly red test (exit 1). Works");
        w.WriteLine("                          together with --watch (a cycle with a missing symbol falls");
        w.WriteLine("                          back to a full rebuild instead of the fast incremental");
        w.WriteLine("                          path — the console names the reason). Not yet supported");
        w.WriteLine("                          together with --server.");
        w.WriteLine("  --per-suite             Legacy per-Compilation path. Default is bundled mode");
        w.WriteLine("                          (5-7x faster, parity-verified).");
        w.WriteLine("  --bundled               No-op alias for the default bundled mode (deprecated).");
        w.WriteLine("  --define SYM            Define an AL preprocessor symbol for source compilation");
        w.WriteLine("                          (repeatable). SYM must be a valid AL identifier");
        w.WriteLine("                          (letters/digits/underscores, not starting with a digit).");
        w.WriteLine("                          Merged with the built-in CLEANSCHEMA1..25 set.");
        w.WriteLine("  --preprocessor-symbols A,B,...");
        w.WriteLine("                          Define multiple AL preprocessor symbols (comma-separated).");
        w.WriteLine("                          Each entry is validated identically to --define.");
        w.WriteLine();
        w.WriteLine("OUTPUT");
        w.WriteLine("  --out PATH              Write the failure-classification JSON to PATH and");
        w.WriteLine("                          print the FAILURE CLASSIFICATION block. Off by default —");
        w.WriteLine("                          classification is a runner-development diagnostic.");
        w.WriteLine("  --classify              Print the FAILURE CLASSIFICATION block without writing");
        w.WriteLine("                          a JSON file.");
        w.WriteLine("  --output-json           Replace the normal text output with per-test JSON on");
        w.WriteLine("                          stdout (status: pass/fail/error, message, stackTrace,");
        w.WriteLine("                          durationMs, exitCode). Distinct from --out's failure-");
        w.WriteLine("                          classification JSON.");
        w.WriteLine("  --output-junit PATH     Write a JUnit XML report to PATH, grouped by codeunit.");
        w.WriteLine("                          Independent of --output-json — works with either mode.");
        w.WriteLine("  --coverage              Statement-level coverage via BC's own StmtHit");
        w.WriteLine("                          instrumentation (no rewrite of emitted AL output —");
        w.WriteLine("                          the hook lives in Ncl.dll). Writes Cobertura XML");
        w.WriteLine("                          (default ./cobertura.xml) plus a console table after");
        w.WriteLine("                          the run. Off by default; --coverage-out PATH overrides");
        w.WriteLine("                          the Cobertura output path.");
        w.WriteLine("  --failures-only, --quiet");
        w.WriteLine("                          Print only FAIL/ERROR per-test lines. Default prints both");
        w.WriteLine("                          PASS and FAIL with stack traces (matches v1).");
        w.WriteLine("  --show-pass             Accepted for v1 back-compat; PASS lines are on by default");
        w.WriteLine("                          in v2.");
        w.WriteLine("  --verbose               Show internal [Component] diagnostic logs.");
        w.WriteLine("  --strict                Accepted for back-compat; this is the default since the v2");
        w.WriteLine("                          cut. Exit codes:");
        w.WriteLine("                            0  all tests passed");
        w.WriteLine("                            1  at least one test FAILED or ERRORED");
        w.WriteLine("                            2  a bundle could not execute (process-level error;");
        w.WriteLine("                               also a bad invocation — unknown flag, or a bundle");
        w.WriteLine("                               path that does not exist)");
        w.WriteLine("                            3  a bundle could not compile");
        w.WriteLine("                            4  --count-baseline: a suite's test or app-group count did");
        w.WriteLine("                               not exactly match its declared baseline (see --count-baseline)");
        w.WriteLine("  --no-strict-exit        Always exit 0 regardless of test outcome, so callers can");
        w.WriteLine("                          parse the JSON output without the process failing the step.");
        w.WriteLine("  --dump-csharp DIR       Write the intermediate C# emitted by BC's Compilation.Emit");
        w.WriteLine("                          (one .cs file per AL object) under DIR/<moduleName>/.");
        w.WriteLine("                          Useful for diagnosing codegen issues.");
        w.WriteLine("  --expectations DIR      Load the test-expectations manifest from DIR (schema:");
        w.WriteLine("                          docs/expectations.md). Defaults to ./tests/expectations");
        w.WriteLine("                          when that directory exists; otherwise off. Declared");
        w.WriteLine("                          outcomes reclassify: expect-oos -> pass-oos,");
        w.WriteLine("                          expect-fail-known-gap -> pass-known-gap,");
        w.WriteLine("                          expect-divergence -> pass-divergence, skip -> not");
        w.WriteLine("                          invoked. Manifest drift is loud: an entry whose test now");
        w.WriteLine("                          passes, or an out-of-scope throw with no entry, fails");
        w.WriteLine("                          the run with a diagnostic naming the entry to fix.");
        w.WriteLine("  --count-baseline PATH   Load a per-suite test/app-group expected-count manifest");
        w.WriteLine("                          (schema: AlRunner/Infrastructure/CountBaseline.cs) and");
        w.WriteLine("                          fail the run (exit 4) if a suite's count does not exactly");
        w.WriteLine("                          match its baseline for the selected BC version — the guard");
        w.WriteLine("                          for \"a bundle silently stopped being discovered\" (#1880).");
        w.WriteLine("                          Off by default, unlike --expectations: a baseline sized");
        w.WriteLine("                          for the full corpus must not fire on a narrower run of");
        w.WriteLine("                          the same directory (e.g. one filtered with --test), so");
        w.WriteLine("                          this never auto-activates. A mismatch in EITHER direction");
        w.WriteLine("                          (growth or drop) fails and prints a diagnostic naming");
        w.WriteLine("                          expected vs actual — bump the baseline in the same PR.");
        w.WriteLine();
        w.WriteLine("SUBCOMMANDS");
        w.WriteLine("  provision [<bundle-dir>] Download and install the BC artifacts matching the");
        w.WriteLine("                          project's version, then exit without running tests.");
        w.WriteLine("                          This is the supported way to obtain artifacts on a");
        w.WriteLine("                          fresh machine — including a plain `dotnet tool install`");
        w.WriteLine("                          with no source checkout. Run `al-runner provision --help`");
        w.WriteLine("                          for its full flag list, or use one of:");
        w.WriteLine("                            --platform-apps [--bc-version V] [--force]");
        w.WriteLine("                                          Force-download Microsoft's platform .app");
        w.WriteLine("                                          set into the canonical dir, bypassing");
        w.WriteLine("                                          need-detection.");
        w.WriteLine("                            --test-apps [--bc-version V] [--force]");
        w.WriteLine("                                          Same, for the Microsoft test-toolkit set.");
        w.WriteLine("                            --service-tier [--bc-version V] [--force]");
        w.WriteLine("                                          Same, for the BC engine's service-tier DLLs.");
        w.WriteLine("                            --resolve-version PREFIX");
        w.WriteLine("                                          Print the latest full BC version for a");
        w.WriteLine("                                          prefix (e.g. \"28.4\") to stdout.");
        w.WriteLine("                          --force re-downloads even when the target directory");
        w.WriteLine("                          already looks populated (default: leave it alone).");
        w.WriteLine("  --precompile <input.app> --out <output.dll> [--package-cache PATH ...]");
        w.WriteLine("                          Compile a single .app to a managed DLL without running");
        w.WriteLine("                          tests. Useful for pre-warming caches.");
        w.WriteLine("  --emit-app <bundleDir> <outPath> [--package-cache PATH ...]");
        w.WriteLine("                          Compile a bundle dir and emit it as a .app package");
        w.WriteLine("                          in-process, without running tests.");
        w.WriteLine();
        w.WriteLine("ENVIRONMENT");
        w.WriteLine("  AL_RUNNER_VERBOSE=1          Same as --verbose.");
        w.WriteLine("  AL_RUNNER_FAILURES_ONLY=1    Same as --failures-only.");
        w.WriteLine("  AL_RUNNER_TRACE_NRE=1        Log every first-chance NullReferenceException with");
        w.WriteLine("                               full stack to stderr before AL `asserterror` swallows it.");
        w.WriteLine("  AL_RUNNER_NCL_CACHE=0        Force fresh Cecil rewrite of Ncl.dll (default: use");
        w.WriteLine("                               ~/.cache/al-runner/ncl-cecil/<key>.dll if present).");
        w.WriteLine("  AL_RUNNER_HOOK_TRACE=1       Trace every JmpHook fire to");
        w.WriteLine("                               /tmp/al-runner-hook-trace.log.");
        w.WriteLine("  AL_RUNNER_EMIT_TIMEOUT_SEC=N Override the 120 s default emit-phase timeout.");
        w.WriteLine("  AL_RUNNER_PHASE_LOG=PATH     Append one JSONL cost record per app group, per");
        w.WriteLine("                               bundle and per process to PATH (emit/compile/run");
        w.WriteLine("                               ms, deps, cache HIT/MISS, start + wall clock,");
        w.WriteLine("                               peak RSS; start_ms + wall_ms give an occupancy");
        w.WriteLine("                               timeline across concurrent runners).");
        w.WriteLine("                               Safe for concurrent runners. Summarise with");
        w.WriteLine("                               scripts/phase-log-report.py. Inert when unset.");
        w.WriteLine();
        w.WriteLine("EXAMPLES");
        w.WriteLine("  # Run the al-language corpus");
        w.WriteLine("  al-runner tests/al-language/tests/al-language");
        w.WriteLine();
        w.WriteLine("  # Run a real app together with its separate test app (the usual shape).");
        w.WriteLine("  # Pass BOTH bundle dirs; deps resolve from each bundle's own .alpackages/ or");
        w.WriteLine("  # the BC artifact cache by default — add --package-cache only if a dep lives");
        w.WriteLine("  # somewhere else.");
        w.WriteLine("  al-runner --bc-version 28.2 MyApp MyApp.Test");
        w.WriteLine();
        w.WriteLine("  # Provision BC artifacts on a fresh machine, then run");
        w.WriteLine("  al-runner provision MyApp");
        w.WriteLine();
        w.WriteLine("  # Run one specific test");
        w.WriteLine("  al-runner --test Record_Insert_DuplicateKey_Throws tests/al-language/tests/al-language");
        w.WriteLine();
        w.WriteLine("  # CI: JUnit report for the test-results tab, strict exit by default");
        w.WriteLine("  al-runner --output-junit ci-results.xml tests/al-language/tests/al-language");
        w.WriteLine();
        w.WriteLine("  # Machine-readable per-test JSON for a scripted caller");
        w.WriteLine("  al-runner --output-json tests/al-language/tests/al-language");
        w.WriteLine();
        w.WriteLine("  # Dump the C# for a debugging session");
        w.WriteLine("  al-runner --dump-csharp /tmp/al-csharp tests/runner-extras/query-join-aggregation-oos");
        w.WriteLine();
        w.WriteLine("  # Pre-compile an .app to a managed DLL");
        w.WriteLine("  al-runner --precompile MyExtension_1.0.0.0.app --out MyExtension.dll");
        w.WriteLine();
        w.WriteLine("NOT YET IMPLEMENTED (see docs/v1-to-v2-migration.md)");
        w.WriteLine("  Nothing in this section is accepted as a flag. Everything documented above IS");
        w.WriteLine("  implemented.");
        w.WriteLine("  --stubs DIR             v1's stub-merge path. Real MS DLLs load in-process so the");
        w.WriteLine("                          original use case mostly evaporated; still possible to");
        w.WriteLine("                          add as an extra source-root merge if needed.");
        w.WriteLine("  --extract-deps          v1's dep-slicer (DepExtractor.cs, ~121 KB). Likely to stay");
        w.WriteLine("                          dropped — the full dep set loads directly instead.");
        w.WriteLine();
        w.WriteLine("DOCUMENTATION");
        w.WriteLine("  al-runner --guide            operating manual: correct invocation against a real");
        w.WriteLine("                               app, dependency resolution, failure signatures");
        w.WriteLine("  docs/v1-to-v2-migration.md  flag-by-flag migration matrix");
        w.WriteLine("  docs/expectations.md         out-of-scope test declarations");
        w.WriteLine("  docs/scope.md                runtime scope (in-scope vs OOS-by-design)");
        w.WriteLine("  docs/limitations.md          architectural limits");
        w.WriteLine("  docs/cecil-migration.md      Cecil rewrite strategy");
    }

    // Issue #2085: `provision --help` used to fall through to the generic arg-parser's
    // unknown-flag error ("Unknown option '--help'. Run with --help for the supported
    // flags.") — telling the caller to run the exact thing it just ran. Every subcommand
    // must answer --help, not just the top level.
    internal static void PrintProvisionHelp(TextWriter w)
    {
        w.WriteLine("al-runner provision — download and install BC artifacts. Every form below works");
        w.WriteLine("from a plain `dotnet tool install -g msdyn365bc.al.runner`; none require a source");
        w.WriteLine("checkout of this repository.");
        w.WriteLine();
        w.WriteLine("USAGE");
        w.WriteLine("  al-runner provision [<bundle-dir>]");
        w.WriteLine("  al-runner provision --platform-apps [--bc-version V] [--force]");
        w.WriteLine("  al-runner provision --test-apps [--bc-version V] [--force]");
        w.WriteLine("  al-runner provision --service-tier [--bc-version V] [--force]");
        w.WriteLine("  al-runner provision --resolve-version PREFIX");
        w.WriteLine("  al-runner provision --help");
        w.WriteLine();
        w.WriteLine("OPTIONS");
        w.WriteLine("  [<bundle-dir>]          With no mode flag: provision everything the named");
        w.WriteLine("                          bundle's app.json needs (engine closure + platform apps");
        w.WriteLine("                          + test toolkit, whichever are missing) and exit. This is");
        w.WriteLine("                          the default `provision` behavior and what a provisioning-");
        w.WriteLine("                          gap error's \"(a) One command (recommended)\" fix means.");
        w.WriteLine("  --bc-version V          Target BC version (a prefix like \"28.4\" or a full");
        w.WriteLine("                          4-part version). Default: this binary's own built");
        w.WriteLine("                          engine version, or the target bundle's app.json.");
        w.WriteLine("  --platform-apps         Force-download Microsoft's platform .app set (Base");
        w.WriteLine("                          Application / System Application / Business Foundation /");
        w.WriteLine("                          Application / Application Test Library) into the");
        w.WriteLine("                          canonical <artifacts>/<version>/platform-apps directory,");
        w.WriteLine("                          bypassing need-detection entirely.");
        w.WriteLine("  --test-apps             Force-download the Microsoft test-toolkit .app set");
        w.WriteLine("                          (Library Assert, Test Runner, Any, Tests-TestLibraries, …)");
        w.WriteLine("                          into <artifacts>/<version>/test-apps, bypassing");
        w.WriteLine("                          need-detection entirely.");
        w.WriteLine("  --service-tier          Force-download the BC engine's ~55-DLL service-tier");
        w.WriteLine("                          closure into <artifacts>/<version>, bypassing");
        w.WriteLine("                          need-detection entirely.");
        w.WriteLine("  --force                 With --platform-apps/--test-apps/--service-tier: re-run");
        w.WriteLine("                          the download even if the canonical directory already");
        w.WriteLine("                          contains files. Without it, a populated directory is");
        w.WriteLine("                          left alone and nothing is re-downloaded.");
        w.WriteLine("  --resolve-version PREFIX");
        w.WriteLine("                          Resolve a BC version prefix (e.g. \"28.4\") to the latest");
        w.WriteLine("                          full version published on the CDN and print it to stdout.");
        w.WriteLine("  --help, -h              Print this text and exit 0.");
        w.WriteLine();
        w.WriteLine("--platform-apps/--test-apps/--service-tier/--resolve-version may be combined in");
        w.WriteLine("one invocation (each named set is fetched); --force applies to all of them.");
    }
}
