namespace AlRunner.Runtime;

using System.Text;
using Microsoft.Dynamics.Nav.Runtime;
using Microsoft.Dynamics.Nav.Types;

/// <summary>
/// Static replacement for ALStream.
/// Routes ALReadText/ALWriteText calls to MockInStream/MockOutStream.
/// </summary>
public static class MockStream
{
    /// <summary>
    /// Default length constant matching ALStream.DefaultLength.
    /// A value of -1 means "read/write all available data".
    /// </summary>
    public static readonly int DefaultLength = -1;

    /// <summary>
    /// ALReadText — reads text from the stream into the ByRef NavText parameter.
    /// Matches: ALStream.ALReadText(INavStreamReader, DataError, ByRef&lt;NavText&gt;, int)
    /// </summary>
    public static int ALReadText(MockInStream reader, DataError dataError, ByRef<NavText> passByRef, int length = -1)
    {
        int maxLen = length < 0 ? int.MaxValue : length;
        string text = "";
        int bytesRead = reader.ReadText(ref text, maxLen);
        passByRef.Value = NavText.Create(text);
        return bytesRead;
    }

    /// <summary>
    /// ALReadText — reads text directly into a ref NavText parameter.
    /// Matches: ALStream.ALReadText(INavStreamReader, DataError, ref NavText, int)
    /// </summary>
    public static int ALReadText(MockInStream reader, DataError dataError, ref NavText value, int length = -1)
    {
        int maxLen = length < 0 ? int.MaxValue : length;
        string text = "";
        int bytesRead = reader.ReadText(ref text, maxLen);
        value = NavText.Create(text);
        return bytesRead;
    }

    /// <summary>
    /// ALWriteText — writes text to the stream.
    /// Matches: ALStream.ALWriteText(INavStreamWriter, DataError, string/NavText, int)
    /// </summary>
    public static int ALWriteText(MockOutStream writer, DataError dataError, NavText value, int length = -1)
    {
        string text = value.ToString();
        if (length >= 0 && length < text.Length)
            text = text.Substring(0, length);
        writer.WriteText(text);
        return Encoding.UTF8.GetByteCount(text);
    }

    /// <summary>
    /// ALWriteText — writes a string to the stream.
    /// </summary>
    public static int ALWriteText(MockOutStream writer, DataError dataError, string value, int length = -1)
    {
        string text = value;
        if (length >= 0 && length < text.Length)
            text = text.Substring(0, length);
        writer.WriteText(text);
        return Encoding.UTF8.GetByteCount(text);
    }

    /// <summary>
    /// ALWriteText — no-arg overload (writes empty line / newline).
    /// Matches: ALStream.ALWriteText(INavStreamWriter, DataError)
    /// </summary>
    public static int ALWriteText(MockOutStream writer, DataError dataError)
    {
        writer.WriteText("");
        return 0;
    }

    /// <summary>
    /// ALWriteString — writes a C# string value to the stream.
    /// Matches: ALStream.ALWriteString(INavStreamWriter, DataError, string)
    /// Generated by the BC compiler when writing string-typed values to an OutStream
    /// (e.g. OutStream.Write(text) where the compiler resolves the value to a string type).
    /// In stream mode the mock writes the UTF-8 bytes; no binary-framing null terminator
    /// is added since the mock does not implement NavStreamMode.FileBinary.
    /// </summary>
    public static int ALWriteString(MockOutStream writer, DataError dataError, string value)
    {
        writer.WriteText(value);
        return Encoding.UTF8.GetByteCount(value);
    }

    /// <summary>
    /// ALWriteString — with an explicit length limit.
    /// Matches: ALStream.ALWriteString(INavStreamWriter, DataError, string, int)
    /// </summary>
    public static int ALWriteString(MockOutStream writer, DataError dataError, string value, int length)
    {
        string text = (length >= 0 && length < value.Length) ? value.Substring(0, length) : value;
        writer.WriteText(text);
        return Encoding.UTF8.GetByteCount(text);
    }

    /// <summary>
    /// ALWriteString — NavText overload.
    /// Some BC compiler versions emit ALWriteString for NavText values
    /// (e.g. OutStream.Write(NavText)) to distinguish the null-terminated string
    /// format from the plain WriteText format.
    /// </summary>
    public static int ALWriteString(MockOutStream writer, DataError dataError, NavText value, int length = -1)
    {
        string text = value.ToString();
        if (length >= 0 && length < text.Length)
            text = text.Substring(0, length);
        writer.WriteText(text);
        return Encoding.UTF8.GetByteCount(text);
    }

    /// <summary>
    /// ALWrite — writes a NavText value to the stream as bytes.
    /// </summary>
    public static int ALWrite(MockOutStream writer, DataError dataError, NavText value, int length = -1)
    {
        return ALWriteText(writer, dataError, value, length);
    }

    /// <summary>
    /// ALWrite — writes a string value to the stream as bytes.
    /// </summary>
    public static int ALWrite(MockOutStream writer, DataError dataError, string value, int length = -1)
    {
        return ALWriteText(writer, dataError, value, length);
    }

    /// <summary>
    /// ALRead — reads from stream into ByRef NavText.
    /// </summary>
    public static int ALRead(MockInStream reader, DataError dataError, ByRef<NavText> passByRef, int length = -1)
    {
        return ALReadText(reader, dataError, passByRef, length);
    }

    /// <summary>
    /// ALWrite — writes an integer value to the stream as little-endian bytes.
    /// Matches: ALStream.ALWrite(INavStreamWriter, DataError, int)
    /// </summary>
    public static int ALWrite(MockOutStream writer, DataError dataError, int value, int length = -1)
    {
        byte[] bytes = BitConverter.GetBytes(value);
        if (!BitConverter.IsLittleEndian) Array.Reverse(bytes);
        writer.Write(bytes, 0, bytes.Length);
        return bytes.Length;
    }

    /// <summary>
    /// ALRead — reads an integer from the stream (little-endian bytes).
    /// </summary>
    public static int ALRead(MockInStream reader, DataError dataError, ByRef<int> passByRef)
    {
        byte[] bytes = new byte[4];
        int read = reader.Read(bytes, 0, 4);
        if (!BitConverter.IsLittleEndian) Array.Reverse(bytes);
        passByRef.Value = BitConverter.ToInt32(bytes, 0);
        return read;
    }

    /// <summary>
    /// ALWrite — writes a boolean value to the stream as a single byte.
    /// Matches: ALStream.ALWrite(INavStreamWriter, DataError, bool)
    /// </summary>
    public static int ALWrite(MockOutStream writer, DataError dataError, bool value, int length = -1)
    {
        writer.Write(new byte[] { value ? (byte)1 : (byte)0 }, 0, 1);
        return 1;
    }

    /// <summary>
    /// ALRead — reads a boolean from the stream (single byte).
    /// </summary>
    public static int ALRead(MockInStream reader, DataError dataError, ByRef<bool> passByRef)
    {
        byte[] b = new byte[1];
        int read = reader.Read(b, 0, 1);
        passByRef.Value = b[0] != 0;
        return read;
    }

    /// <summary>
    /// ALWrite — writes a Decimal18 value to the stream as little-endian decimal bytes.
    /// Matches: ALStream.ALWrite(INavStreamWriter, DataError, Decimal18)
    /// </summary>
    public static int ALWrite(MockOutStream writer, DataError dataError, Decimal18 value, int length = -1)
    {
        decimal d = (decimal)value;
        int[] bits = decimal.GetBits(d);
        byte[] bytes = new byte[16];
        for (int i = 0; i < 4; i++)
        {
            byte[] part = BitConverter.GetBytes(bits[i]);
            if (!BitConverter.IsLittleEndian) Array.Reverse(part);
            Array.Copy(part, 0, bytes, i * 4, 4);
        }
        writer.Write(bytes, 0, bytes.Length);
        return bytes.Length;
    }

    /// <summary>
    /// ALRead — reads a Decimal18 from the stream (16 little-endian bytes).
    /// </summary>
    public static int ALRead(MockInStream reader, DataError dataError, ByRef<Decimal18> passByRef)
    {
        byte[] bytes = new byte[16];
        int read = reader.Read(bytes, 0, 16);
        int[] bits = new int[4];
        for (int i = 0; i < 4; i++)
        {
            byte[] part = new byte[4];
            Array.Copy(bytes, i * 4, part, 0, 4);
            if (!BitConverter.IsLittleEndian) Array.Reverse(part);
            bits[i] = BitConverter.ToInt32(part, 0);
        }
        decimal d = new decimal(bits);
        passByRef.Value = new Decimal18(d);
        return read;
    }

    /// <summary>
    /// ALCopyStream — copies all bytes from InStream to OutStream.
    /// Intercepts ALSystemVariable.ALCopyStream(DataError, NavOutStream, NavInStream).
    /// </summary>
    public static void ALCopyStream(DataError dataError, MockOutStream writer, MockInStream reader)
    {
        byte[] buf = new byte[4096];
        int read;
        while ((read = reader.Read(buf, 0, buf.Length)) > 0)
            writer.Write(buf, 0, read);
    }
}
