// Source for issue #1442 — CS1503: object → string in TestPage filter operations.
//
// After #1417 changed MockTestPageField.ALValue from object? to string, standard
// BC page test code that was previously masked by the ALValue CS1503 became
// visible.  The remaining errors are from MockTestPageFilter.ALSetFilter(int, string)
// receiving object-typed arguments (NavComplexValue → object after the rewriter)
// for certain complex filter patterns generated by BC for standard pages.
//
// This suite validates that TestPage.Filter.SetFilter works correctly when the
// filter expression comes from complex sources (Variant, code-path-dependent values).

table 313000 "FOS Table"
{
    DataClassification = CustomerContent;

    fields
    {
        field(1; "No."; Code[20])
        {
            Caption = 'No.';
        }
        field(2; "Description"; Text[100])
        {
            Caption = 'Description';
        }
        field(3; "Amount"; Decimal)
        {
            Caption = 'Amount';
        }
        field(4; "Active"; Boolean)
        {
            Caption = 'Active';
        }
    }

    keys
    {
        key(PK; "No.")
        {
            Clustered = true;
        }
    }
}

page 313000 "FOS Card"
{
    PageType = List;
    SourceTable = "FOS Table";
    Caption = 'FOS Card';
    ApplicationArea = All;

    layout
    {
        area(Content)
        {
            repeater(Lines)
            {
                field("No."; Rec."No.") { ApplicationArea = All; }
                field(Description; Rec.Description) { ApplicationArea = All; }
                field(Amount; Rec.Amount) { ApplicationArea = All; }
                field(Active; Rec.Active) { ApplicationArea = All; }
            }
        }
    }
}

codeunit 313000 "FOS Helper"
{
    procedure GetFilterText(): Text
    begin
        exit('A001..A999');
    end;

    procedure GetFilterVariant(): Variant
    var
        v: Variant;
    begin
        v := 'A001..A999';
        exit(v);
    end;

    procedure InsertRecord("No.": Code[20]; Desc: Text; Amt: Decimal)
    var
        Rec: Record "FOS Table";
    begin
        if Rec.Get("No.") then
            exit;
        Rec.Init();
        Rec."No." := "No.";
        Rec.Description := Desc;
        Rec.Amount := Amt;
        Rec.Active := true;
        Rec.Insert();
    end;

    procedure DeleteAll()
    var
        Rec: Record "FOS Table";
    begin
        Rec.DeleteAll();
    end;
}
