codeunit 50913 "Report Label Tests"
{
    Subtype = Test;

    var
        Assert: Codeunit Assert;

    [Test]
    procedure TestReportLabelTitle()
    var
        Helper: Codeunit "Report Label Helper";
    begin
        // Report labels should compile and be accessible via report procedures
        Assert.AreEqual('Invoice Report', Helper.GetReportTitle(), 'Title label should be preserved in report class');
    end;

    [Test]
    procedure TestReportLabelSubtitle()
    var
        Helper: Codeunit "Report Label Helper";
    begin
        Assert.AreEqual('Generated by AL Runner', Helper.GetReportSubtitle(), 'Subtitle label should be preserved in report class');
    end;

    [Test]
    procedure TestReportLabelNotEmpty()
    var
        Helper: Codeunit "Report Label Helper";
    begin
        // Negative test: labels must not be empty (proves the label value is actually wired)
        Assert.AreNotEqual('', Helper.GetReportTitle(), 'Title label must not be empty');
    end;
}
