#!/usr/bin/env python3
"""Find a reviewer's verdict line in a comment body by MARKER, never by position (#4338).

`.claude/agents/reviewer.md` asks a reviewer to end a review comment with

    Verdict: MERGE|FIX-FIRST|HOLD (<reason>) — head <full 40-char sha>

and `orchestrating-a-session`'s arming step reads that line for the decision and
for the head the verdict is about. The contract used to be positional -- "the
posted comment's last line" -- and that does not survive the transport: in a
session with no `gh` (every web and remote session, `github-access.md`) the
reviewer posts through `mcp__github__add_issue_comment` and an attribution
footer is appended after the body, so the last line is the footer.

Measured over the 60 most recent pull requests on 2026-09-19 -- 150 comments
carrying a `^Verdict:` line:

    124  the verdict line IS the last non-blank line
     26  a `_Generated by [Claude Code](...)_` footer sits below it

The footer accounts for all 26; nothing else displaces the line. So this is
deterministic and environment-split, not occasional.

Why searching rather than "have the reviewer append the footer itself": that
would encode one transport's current behaviour into an agent definition, where
the next change to it breaks the arming step silently. A marker survives any
footer, any transport, and a human replying underneath.

THE MARKER, and why this shape

`Verdict:` at the START of a line, bare -- no leading whitespace, no bold. From
the same scan the bare form occurs in all 150 comments, so the anchor misses
nothing that exists. Bold is deliberately NOT accepted: it is never the only
marker (0 of 150) and it does occur as prose (2 of 150,
`**Verdict: this meets the merge bar.** ...`), so tolerating it only manufactures
two-marker refusals on comments the bare anchor reads correctly.

The start-of-line anchor is load-bearing rather than tidy. Review prose uses the
word constantly: PR #4376 alone carries "Verdict at the end.", a "### Verdict"
heading and a "| verdict |" table column. A substring search finds those and
reads a head SHA out of a sentence.

THE THREE ANSWERS (`guards-need-a-third-state.md`)

    0  found      -- one well-formed marker line; the requested field is on stdout
    2  not found  -- no marker line. NOT a fallback to the last line: an
                     extractor that falls back has reproduced the defect, since
                     it returns the footer, well-formed, and the caller then
                     reads a head SHA that is not there.
    3  malformed  -- a marker line that cannot be used: an abbreviated head, an
                     unknown decision, no head at all, or two marker lines. Kept
                     distinct from 2 because "no verdict was posted" and "the
                     verdict posted is unusable" send the reader to different
                     remedies.
    4  unreadable -- the comments could not be fetched or parsed at all. Kept
                     distinct from 3 for the same reason again: this one is a
                     fact about the box, not about any review.

Note what is NOT in that list: exit 1. A verdict reader exiting 1 reads as "a
verdict was found and it was negative", so every failure mode here is given a
code that cannot be mistaken for one.

Two marker lines refuse rather than pick one: zero of the 150 measured comments
carry two, so there is no established precedence to apply and guessing one makes
the tool silently report a verdict nobody wrote.

Usage
    gh api repos/<o>/<r>/issues/<N>/comments --jq '.[-1].body' \
      | tools/review-verdict.py --stdin --field head
    tools/review-verdict.py --pr <N> --repo <owner>/<repo> --field decision

Run the guard: python3 tools/test_review_verdict.py
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys

# A verdict line carries an em dash, and its reason is free text a reviewer
# wrote. Printing either through the console codec raises UnicodeEncodeError on
# a cp1252 box -- the failure `ci-verdicts.md` records for a tool copied without
# this sibling, where the exit code then means something else entirely.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
try:
    import agent_stdio as _stdio
except Exception:  # pragma: no cover - a copy detached from its sibling module
    _stdio = None
if _stdio is not None:
    _stdio.enable_utf8_stdio()

# Four answers, not three. UNREADABLE is deliberately distinct from MALFORMED:
# "the verdict posted is unusable" is a fact about a review someone wrote, while
# "I could not read the comments at all" is a fact about this box, and folding
# the second into the first sends a coordinator to argue with a reviewer about a
# verdict nobody has seen (`guards-need-a-third-state.md`).
#
# It is emphatically not exit 1 either. A verdict reader exiting 1 reads as "a
# verdict was found and it was negative" -- the shape `ci-verdicts.md` records
# for a `ci-wait.py` copy that hit a decode error on a cp1252 box and was taken
# for "a required check failed".
FOUND, NOT_FOUND, MALFORMED, UNREADABLE = 0, 2, 3, 4

# Start of line, bare, no leading whitespace and no bold.
#
# Whitespace tolerance is deliberately NOT granted: indentation is how markdown
# marks quoted and nested content, so a reviewer quoting an earlier verdict
# inside a list or block quote would otherwise match as though they had issued
# one.
#
# Bold tolerance was tried and MEASURED WORSE, which is the opposite of the
# intuition that a reviewer "will write `**Verdict:**`". Over the same 150
# comments: zero carry a bold marker as their ONLY marker, so accepting bold
# rescues nothing -- and two carry a bold PROSE sentence
# (`**Verdict: this meets the merge bar.** The fix is correct, ...`, PRs #4354
# and #4291) alongside the real line, so accepting bold turns those into
# two-marker refusals. Widening the matcher here would refuse two verdicts that
# the bare anchor reads correctly.
MARKER = re.compile(r'^Verdict:(?P<rest>.*)$')

DECISIONS = ("MERGE", "FIX-FIRST", "HOLD")

# `— head <sha>`: the em dash is what reviewer.md specifies, but a hyphen is
# accepted because the two are indistinguishable to a reader and an agent
# retyping the line will produce either.
HEAD = re.compile(r'[—-]\s*head\s+(?P<sha>[0-9a-fA-F]+)\s*$')


def find_marker_lines(body: str) -> list[str]:
    # GitHub returns comment bodies with CRLF. Strip the \r here rather than at
    # the point of use: a carriage return left on the end of a SHA makes a
    # compare against `headRefOid` fail while the two look identical printed.
    return [m.group(0) for m in
            (MARKER.match(line) for line in body.replace("\r\n", "\n").split("\n"))
            if m]


def parse(line: str) -> tuple[dict[str, str] | None, str]:
    """Return (fields, error). fields is None when the line cannot be used."""
    rest = MARKER.match(line).group("rest").strip()

    m = HEAD.search(rest)
    if not m:
        return None, "no `— head <sha>` on the marker line"
    sha = m.group("sha")
    if len(sha) != 40:
        return None, f"head `{sha}` is {len(sha)} chars, not a full 40-char SHA"

    head_part = rest[:m.start()].strip()

    reason = ""
    if head_part.endswith(")") and "(" in head_part:
        open_at = head_part.index("(")
        reason = head_part[open_at + 1:-1].strip()
        decision = head_part[:open_at].strip()
    else:
        decision = head_part

    if decision not in DECISIONS:
        return None, f"decision `{decision}` is not one of {', '.join(DECISIONS)}"
    # MERGE carrying a reason is accepted but reported, since reviewer.md says
    # MERGE carries none -- it is a wording slip, not an unusable verdict.
    return {"line": line.strip(), "decision": decision, "reason": reason,
            "head": sha.lower()}, ""


def body_from_pr(pr: str, repo: str) -> str:
    """The newest comment on the PR that carries a marker line."""
    try:
        out = subprocess.run(
            ["gh", "api", f"repos/{repo}/issues/{pr}/comments", "--paginate"],
            capture_output=True, text=True, encoding="utf-8", errors="replace")
    except OSError as exc:  # no `gh` at all -- every web and remote session
        print(f"could not run `gh`: {exc}. Without it, read the comment body "
              "yourself and pipe it in with --stdin (`github-access.md`).",
              file=sys.stderr)
        sys.exit(UNREADABLE)
    if out.returncode:
        print(f"could not read comments for PR {pr}: {out.stderr.strip()}",
              file=sys.stderr)
        sys.exit(UNREADABLE)
    try:
        comments = json.loads(out.stdout or "[]")
    except json.JSONDecodeError as exc:
        # A truncated or non-JSON response is a failed measurement, not a
        # verdict-free PR: returning "" here would print "no verdict line" and
        # send the reader to chase a reviewer who may well have posted one.
        print(f"could not parse the comments for PR {pr}: {exc}", file=sys.stderr)
        sys.exit(UNREADABLE)
    for c in reversed(comments):
        if find_marker_lines(c.get("body") or ""):
            return c["body"]
    return ""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--stdin", action="store_true", help="read the body on stdin")
    src.add_argument("--pr", help="read the newest verdict-bearing comment on this PR")
    ap.add_argument("--repo", default="StefanMaron/BusinessCentral.AL.Runner")
    ap.add_argument("--field", default="line",
                    choices=("line", "decision", "reason", "head"))
    ap.add_argument("--expect-head",
                    help="also require the verdict's head to equal this SHA")
    args = ap.parse_args()

    body = sys.stdin.read() if args.stdin else body_from_pr(args.pr, args.repo)

    lines = find_marker_lines(body)
    if not lines:
        print("no verdict line: no line starts with `Verdict:`. "
              "NOT falling back to the last line -- that is the footer (#4338).",
              file=sys.stderr)
        return NOT_FOUND
    if len(lines) > 1:
        print(f"{len(lines)} verdict lines in one comment; refusing to pick one:",
              file=sys.stderr)
        for line in lines:
            print(f"  {line.strip()}", file=sys.stderr)
        return MALFORMED

    fields, err = parse(lines[0])
    if fields is None:
        print(f"malformed verdict line: {err}\n  {lines[0].strip()}", file=sys.stderr)
        return MALFORMED

    if args.expect_head and fields["head"] != args.expect_head.lower():
        print(f"verdict is about {fields['head']}, not {args.expect_head} "
              "-- the head moved since it was posted", file=sys.stderr)
        return MALFORMED

    print(fields[args.field])
    return FOUND


if __name__ == "__main__":
    sys.exit(main())
