#!/usr/bin/env python3
"""Every `tools/*.py` command an agent definition PRESCRIBES must actually run.

Issue #4347 moved `reviewer.md`'s comment-vs-code figure off a hand-rolled `awk`
one-liner and onto `tools/comment-density.py diff`. That trade is the right one --
the recipe's defect was its BASE, and a tool can hold the base where a shell
history cannot -- but it creates a dependency nothing was checking: the
instruction now names a subcommand and a flag, and a rename in `tools/` leaves
`.claude/agents/*.md` telling every reviewer to run something that no longer
exists.

The failure is silent in the direction that matters. An agent handed a dead
command reports that it could not take the measurement, or -- worse, and this is
the shape `guards-need-a-third-state.md` is about -- quietly falls back to
whatever it can compute, which is the hand-rolled diff this change removed.

So: extract every `tools/<name>.py <subcommand> [--flags]` invocation from the
agent definitions and require, for each, that the script exists, that the
subcommand is a real subparser, and that each long flag is accepted there.

Deliberately NOT checked
------------------------
Whether the command produces a correct ANSWER. That is the business of
`test_comment_density_diff.py` and its siblings, which pin the measurement
itself against #4347's own figures. This guard pins only the wiring, which is
the half that had no owner.

Usage text is read from `--help`, and only from the `usage:` line it prints. A
script whose `--help` cannot be read is unmeasurable and REFUSES (exit 3)
rather than passing: a command that could not be read is not a command that was
verified. There is no bare-invocation fallback -- see `help_text`.

A bare mention with no subcommand and no flags (`use tools/lsp-query.py`)
prescribes nothing beyond the file, so its existence is the whole check.
"""

import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
AGENT_DIR = REPO / ".claude" / "agents"

failures: list[str] = []
refusals: list[str] = []
checked = 0
interrogated = 0


def check(name: str, cond: bool, detail: str = "") -> None:
    global checked
    checked += 1
    if cond:
        print(f"  ok   {name}")
    else:
        failures.append(f"{name}: {detail}")
        print(f"  FAIL {name}: {detail}")


# A prescribed invocation: `tools/<script>.py <sub> --flag ...` inside a fenced
# block or inline code. Subcommand must be a bare word (not a flag, not a
# placeholder like <branch>); flags are captured for membership checking.
INVOCATION = re.compile(
    r"\btools/([A-Za-z0-9_.-]+\.py)"          # the script
    r"((?:[ \t]+(?:--?[A-Za-z0-9][\w-]*(?:[ \t]+(?:<[^>]+>|[^\s<>]+))?"
    r"|<[^>]+>|[A-Za-z][\w-]*))*)"            # the argument tail
)

LONG_FLAG = re.compile(r"--[A-Za-z][\w-]*")


def _run(argv: list[str]) -> tuple[int, str] | None:
    try:
        p = subprocess.run(argv, capture_output=True, text=True, timeout=60,
                           cwd=str(REPO))
    except (OSError, subprocess.SubprocessError):
        return None
    return p.returncode, (p.stdout or "") + (p.stderr or "")


USAGE_LINE = re.compile(r"^usage:(.*?)(?=\n\S|\n\n|\Z)", re.S | re.M)


def usage_block(text: str) -> str:
    """Just the `usage:` line(s) -- never the description or epilog.

    This distinction is the guard, not a tidiness measure. A renamed subcommand
    falls through to the TOP-LEVEL parser, which prints its own `--help` at exit
    0, and these scripts document their subcommands in the module docstring that
    argparse prints as the description. So `"diff" in help_text` and
    `"--since" in help_text` both answer True for a script that no longer has a
    `diff` subcommand at all -- measured: renaming it left all 22 checks green.

    The usage line is generated by the parser that actually ran, so it cannot
    name a flag that parser does not accept (`a-substring-test-is-not-a-pin`).
    """
    return "".join(m.group(0) for m in USAGE_LINE.finditer(text))


def help_text(script: Path, sub: str | None) -> str | None:
    """`--help` usage text for a script or subcommand; None if it refused.

    There is deliberately NO fallback to a bare invocation, and the reasoning is
    the whole point of `usage_block` above.

    An earlier revision fell back to running the script with no arguments when
    `--help` failed, citing `lsp-query.py`, which hand-rolls its CLI and answers
    `unknown command '--help'`. Review (#4414) established that both halves of
    that were wrong. It never fires -- `lsp-query.py` is a bare MENTION in the
    prose, no subcommand and no flags, so it is skipped before reaching here,
    and all 11 interrogated invocations accept `--help`. And if it did fire it
    would be actively harmful: a bare run prints the TOP-LEVEL usage, which
    advertises subcommands and flags this particular invocation was never shown
    to accept -- reintroducing exactly the defect `usage_block` exists to
    remove, one level down.

    So a script whose `--help` cannot be read is unmeasurable and refuses. If a
    hand-rolled CLI is ever prescribed WITH a subcommand or flag, this refuses
    loudly and someone teaches the guard to interrogate that CLI properly --
    which is the correct outcome, and the one a silent fallback would hide.
    """
    got = _run([sys.executable, str(script)] + ([sub] if sub else []) + ["--help"])
    if got is not None and got[0] == 0:
        return usage_block(got[1]) or got[1]

    detail = got[1].strip().splitlines()[-1:] if got else ["subprocess failed"]
    refusals.append(
        f"{script.name}{' ' + sub if sub else ''}: --help could not be read "
        f"({detail or ['(no output)']})")
    return None


print("agent definitions prescribe commands that exist")

md_files = sorted(AGENT_DIR.glob("*.md"))
check("there are agent definitions to scan", bool(md_files),
      f"no *.md under {AGENT_DIR}")

seen: set[tuple[str, str | None, frozenset[str]]] = set()
for md in md_files:
    text = md.read_text(encoding="utf-8")
    for m in INVOCATION.finditer(text):
        script_name, tail = m.group(1), m.group(2) or ""
        words = tail.split()
        sub = None
        if words and not words[0].startswith("-") and not words[0].startswith("<"):
            sub = words[0]
        flags = frozenset(LONG_FLAG.findall(tail))
        seen.add((script_name, sub, flags))

# A floor on the POPULATION, not only on the verdict. Breaking the flag regex
# alone takes the run from 22 checks to 3 and still prints "all 3 ... passed"
# at exit 0 (measured in review of #4414): the guard stops seeing and therefore
# stops complaining, which is indistinguishable from a clean repository.
#
# `bool(seen)` cannot catch that -- it is satisfied by one surviving match. The
# floors below are deliberately under the current figures (17 invocations, 11
# interrogated, 22 checks) so that ordinary prose edits do not red the guard,
# while the 86% collapse that a broken extractor produces cannot pass. Raise
# them only alongside a measurement; a floor tightened to today's exact count
# turns every legitimate edit into a failure.
MIN_INVOCATIONS = 10
MIN_INTERROGATED = 6

check("at least one prescribed tools/ invocation was found", bool(seen),
      "the extractor matched nothing -- it has probably drifted from the prose")
check(f"the extractor still sees a plausible population (>= {MIN_INVOCATIONS})",
      len(seen) >= MIN_INVOCATIONS,
      f"only {len(seen)} invocation(s) extracted from {len(md_files)} agent "
      f"definition(s); a regex that matches less is a guard going blind, not a "
      f"repository that got smaller")

for script_name, sub, flags in sorted(seen, key=lambda t: (t[0], t[1] or "")):
    script = REPO / "tools" / script_name
    label = f"{script_name}" + (f" {sub}" if sub else "")
    if not script.exists():
        check(f"{label} -- script exists", False, f"no such file: tools/{script_name}")
        continue

    if sub is None and not flags:
        # A bare mention (`use tools/lsp-query.py`) prescribes no surface to
        # verify beyond the file, which exists. Nothing to interrogate.
        continue

    interrogated += 1
    text = help_text(script, sub)
    if text is None:
        continue  # recorded as a refusal; reported below

    if sub:
        # A real subcommand's own parser prints `usage: <prog> <sub> ...`. A
        # renamed one falls through to the top-level parser, whose usage line
        # names the script alone -- which is what makes this discriminate.
        check(f"{label} -- subcommand accepted", sub in text,
              f"`{sub}` absent from the usage line argparse actually printed "
              f"(got: {' '.join(text.split())[:120]!r})")

    for flag in sorted(flags):
        check(f"{label} {flag} -- accepted", flag in text,
              f"{flag} not in --help for {label}")

check(f"enough invocations carried a surface to interrogate (>= {MIN_INTERROGATED})",
      interrogated >= MIN_INTERROGATED,
      f"only {interrogated} invocation(s) named a subcommand or a flag; if the "
      f"argument-tail regex breaks, every invocation degrades to a bare mention "
      f"and this suite verifies nothing but that some files exist")

print()
if refusals:
    print("REFUSED -- could not establish what these accept:")
    for r in refusals:
        print(f"  {r}")
    print("\nA command that cannot be interrogated is not a command that was "
          "verified (guards-need-a-third-state.md).")
    sys.exit(3)

if failures:
    print(f"{len(failures)} of {checked} checks failed:")
    for f in failures:
        print(f"  {f}")
    sys.exit(1)

print(f"all {checked} prescribed-command checks passed")
