#!/usr/bin/env python3
"""Every `tools/*.py` command an agent definition PRESCRIBES must actually run.

Issue #4347 moved `reviewer.md`'s comment-vs-code figure off a hand-rolled `awk`
one-liner and onto `tools/comment-density.py diff`. That trade is the right one --
the recipe's defect was its BASE, and a tool can hold the base where a shell
history cannot -- but it creates a dependency nothing was checking: the
instruction now names a subcommand and a flag, and a rename in `tools/` leaves
`.claude/agents/*.md` telling every reviewer to run something that no longer
exists.

The failure is silent in the direction that matters. An agent handed a dead
command reports that it could not take the measurement, or -- worse, and this is
the shape `guards-need-a-third-state.md` is about -- quietly falls back to
whatever it can compute, which is the hand-rolled diff this change removed.

So: extract every `tools/<name>.py <subcommand> [--flags]` invocation from the
agent definitions and require, for each, that the script exists, that the
subcommand is a real subparser, and that each long flag is accepted there.

Deliberately NOT checked
------------------------
Whether the command produces a correct ANSWER. That is the business of
`test_comment_density_diff.py` and its siblings, which pin the measurement
itself against #4347's own figures. This guard pins only the wiring, which is
the half that had no owner.

Usage text is what establishes the flags, read from `--help` or, for the scripts
here that hand-roll their CLI and reject it, from a bare invocation. A script
neither form can interrogate is unmeasurable and REFUSES (exit 3) rather than
passing: a command that could not be read is not a command that was verified.

A bare mention with no subcommand and no flags (`use tools/lsp-query.py`)
prescribes nothing beyond the file, so its existence is the whole check.
"""

import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
AGENT_DIR = REPO / ".claude" / "agents"

failures: list[str] = []
refusals: list[str] = []
checked = 0


def check(name: str, cond: bool, detail: str = "") -> None:
    global checked
    checked += 1
    if cond:
        print(f"  ok   {name}")
    else:
        failures.append(f"{name}: {detail}")
        print(f"  FAIL {name}: {detail}")


# A prescribed invocation: `tools/<script>.py <sub> --flag ...` inside a fenced
# block or inline code. Subcommand must be a bare word (not a flag, not a
# placeholder like <branch>); flags are captured for membership checking.
INVOCATION = re.compile(
    r"\btools/([A-Za-z0-9_.-]+\.py)"          # the script
    r"((?:[ \t]+(?:--?[A-Za-z0-9][\w-]*(?:[ \t]+(?:<[^>]+>|[^\s<>]+))?"
    r"|<[^>]+>|[A-Za-z][\w-]*))*)"            # the argument tail
)

LONG_FLAG = re.compile(r"--[A-Za-z][\w-]*")


def _run(argv: list[str]) -> tuple[int, str] | None:
    try:
        p = subprocess.run(argv, capture_output=True, text=True, timeout=60,
                           cwd=str(REPO))
    except (OSError, subprocess.SubprocessError):
        return None
    return p.returncode, (p.stdout or "") + (p.stderr or "")


USAGE_LINE = re.compile(r"^usage:(.*?)(?=\n\S|\n\n|\Z)", re.S | re.M)


def usage_block(text: str) -> str:
    """Just the `usage:` line(s) -- never the description or epilog.

    This distinction is the guard, not a tidiness measure. A renamed subcommand
    falls through to the TOP-LEVEL parser, which prints its own `--help` at exit
    0, and these scripts document their subcommands in the module docstring that
    argparse prints as the description. So `"diff" in help_text` and
    `"--since" in help_text` both answer True for a script that no longer has a
    `diff` subcommand at all -- measured: renaming it left all 22 checks green.

    The usage line is generated by the parser that actually ran, so it cannot
    name a flag that parser does not accept (`a-substring-test-is-not-a-pin`).
    """
    return "".join(m.group(0) for m in USAGE_LINE.finditer(text))


def help_text(script: Path, sub: str | None) -> str | None:
    """Usage text for a script or subcommand; None if it could not be read.

    `--help` is the argparse path and covers almost everything here. A few
    scripts hand-roll their CLI and reject `--help` outright (`lsp-query.py`
    answers `unknown command '--help'`), but print usage on a bare invocation --
    so a refusal from the first form is not yet a refusal, and treating it as
    one would red this guard forever on a healthy repository.
    """
    first = _run([sys.executable, str(script)] + ([sub] if sub else []) + ["--help"])
    if first is not None and first[0] == 0:
        return usage_block(first[1]) or first[1]

    bare = _run([sys.executable, str(script)])
    if bare is not None and bare[1].strip():
        return usage_block(bare[1]) or bare[1]

    detail = first[1].strip().splitlines()[-1:] if first else ["subprocess failed"]
    refusals.append(
        f"{script.name}{' ' + sub if sub else ''}: neither --help nor a bare "
        f"invocation produced usage text ({detail or ['(no output)']})")
    return None


print("agent definitions prescribe commands that exist")

md_files = sorted(AGENT_DIR.glob("*.md"))
check("there are agent definitions to scan", bool(md_files),
      f"no *.md under {AGENT_DIR}")

seen: set[tuple[str, str | None, frozenset[str]]] = set()
for md in md_files:
    text = md.read_text(encoding="utf-8")
    for m in INVOCATION.finditer(text):
        script_name, tail = m.group(1), m.group(2) or ""
        words = tail.split()
        sub = None
        if words and not words[0].startswith("-") and not words[0].startswith("<"):
            sub = words[0]
        flags = frozenset(LONG_FLAG.findall(tail))
        seen.add((script_name, sub, flags))

check("at least one prescribed tools/ invocation was found", bool(seen),
      "the extractor matched nothing -- it has probably drifted from the prose")

for script_name, sub, flags in sorted(seen, key=lambda t: (t[0], t[1] or "")):
    script = REPO / "tools" / script_name
    label = f"{script_name}" + (f" {sub}" if sub else "")
    if not script.exists():
        check(f"{label} -- script exists", False, f"no such file: tools/{script_name}")
        continue

    if sub is None and not flags:
        # A bare mention (`use tools/lsp-query.py`) prescribes no surface to
        # verify beyond the file, which exists. Nothing to interrogate.
        continue

    text = help_text(script, sub)
    if text is None:
        continue  # recorded as a refusal; reported below

    if sub:
        # A real subcommand's own parser prints `usage: <prog> <sub> ...`. A
        # renamed one falls through to the top-level parser, whose usage line
        # names the script alone -- which is what makes this discriminate.
        check(f"{label} -- subcommand accepted", sub in text,
              f"`{sub}` absent from the usage line argparse actually printed "
              f"(got: {' '.join(text.split())[:120]!r})")

    for flag in sorted(flags):
        check(f"{label} {flag} -- accepted", flag in text,
              f"{flag} not in --help for {label}")

print()
if refusals:
    print("REFUSED -- could not establish what these accept:")
    for r in refusals:
        print(f"  {r}")
    print("\nA command that cannot be interrogated is not a command that was "
          "verified (guards-need-a-third-state.md).")
    sys.exit(3)

if failures:
    print(f"{len(failures)} of {checked} checks failed:")
    for f in failures:
        print(f"  {f}")
    sys.exit(1)

print(f"all {checked} prescribed-command checks passed")
