#!/usr/bin/env python3
"""`tools/review-verdict.py` must FIND the verdict line, never read the last one (#4338).

`.claude/agents/reviewer.md` used to state the done-condition as "the posted
comment's last line is the verdict line", and `orchestrating-a-session`'s arming
step read that last line for the verdict and the head SHA it is about. In a
session with no `gh` -- every web and remote session (`github-access.md`) -- a
reviewer posts through `mcp__github__add_issue_comment` and an attribution
footer is appended AFTER the body, so a check keyed on position finds the
footer.

Measured over the 60 most recent pull requests on 2026-09-19, 150 comments carry
a `^Verdict:` line:

    124  the verdict line IS the last non-blank line
     26  a `_Generated by [Claude Code](...)_` footer sits below it

and the footer accounts for ALL 26 -- nothing else displaces the line. So the
positional contract was already failing on 17% of real reviews, deterministically
and silently, with the reviewer unable to suppress the footer.

Same scan, on the marker spelling: `^Verdict:` bare at start-of-line occurs in
all 150 and is never absent, so a strict anchor misses nothing that exists. Bold
occurs in 2, always as a PROSE sentence alongside the real line and never as the
only marker -- so accepting bold would rescue nothing and would instead refuse
those two comments for carrying "two" markers. No comment carries two bare
marker lines, which is what makes "the marker line" unambiguous.

The arm that matters here is the SECOND one. An extractor that falls back to the
last line when it finds no marker has reproduced the defect: it returns the
footer, well-formed, and the arming step then reads a head SHA that is not there.
Refusing is the only safe answer, so `NOT_FOUND` is a distinct exit code from
both "found" and "malformed" (`guards-need-a-third-state.md`).

Run directly: python3 tools/test_review_verdict.py
"""
from __future__ import annotations

import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOOL = os.path.join(ROOT, "tools", "review-verdict.py")

FOOTER = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"
SHA = "fd1ff0c837dbc1777429fdf3602756002bff22c4"

failures: list[str] = []
passes = 0


def check(label: str, ok: bool, detail: str = "") -> None:
    global passes
    if ok:
        passes += 1
        print(f"PASS  {label}")
    else:
        failures.append(label)
        print(f"FAIL  {label}")
        if detail:
            for line in str(detail).splitlines()[:12]:
                print(f"      {line}")


def run(body: str, *args: str) -> tuple[int, str]:
    """Feed a comment body on stdin; return (exit code, stdout)."""
    p = subprocess.run(
        [sys.executable, TOOL, "--stdin", *args],
        input=body, capture_output=True, text=True,
    )
    return p.returncode, p.stdout.strip()


if not os.path.exists(TOOL):
    print(f"FAIL  tools/review-verdict.py does not exist (looked at {TOOL})")
    sys.exit(1)

# ---------------------------------------------------------------- arm 1
# A footer below the verdict line must not displace it. This is the reported
# defect, and the 26/150 population above is exactly this shape.
rc, out = run(f"Looks good.\n\nVerdict: MERGE — head {SHA}{FOOTER}")
check("a footer after the verdict line still yields the verdict line",
      rc == 0 and out == f"Verdict: MERGE — head {SHA}", f"rc={rc} out={out!r}")

rc, out = run(f"Looks good.\n\nVerdict: MERGE — head {SHA}{FOOTER}", "--field", "head")
check("...and the head SHA is read from that line, not from the footer",
      rc == 0 and out == SHA, f"rc={rc} out={out!r}")

rc, out = run(f"Looks good.\n\nVerdict: MERGE — head {SHA}{FOOTER}", "--field", "decision")
check("...and the decision is MERGE", rc == 0 and out == "MERGE", f"rc={rc} out={out!r}")

# ---------------------------------------------------------------- arm 2
# THE ARM THAT MATTERS. A searcher that falls back to the last line when it
# finds no marker has reproduced the defect in a new place.
no_marker = f"Some review prose with no verdict at all.{FOOTER}"
rc, out = run(no_marker)
check("a body with NO verdict line refuses (exit 2) rather than returning the last line",
      rc == 2, f"rc={rc} out={out!r}")
check("...and does not emit the footer as if it were a verdict",
      "Generated by" not in out, f"out={out!r}")

rc, out = run("Just prose. No marker. No footer either.")
check("a body with no verdict line and no footer also refuses",
      rc == 2, f"rc={rc} out={out!r}")

# ---------------------------------------------------------------- arm 3
# The word "verdict" is common in review prose -- PR #4376 carries "Verdict at
# the end.", "### Verdict" and a "| verdict |" table column. A loose matcher
# picks those up and reads a head SHA out of a sentence.
prose = (
    "Reviewed at head `fe0617cf`. Verdict at the end.\n\n"
    "### Verdict and the corpus condition\n\n"
    "| tree | guard | verdict |\n"
    f"\nVerdict: FIX-FIRST (the guard is untested) — head {SHA}{FOOTER}"
)
rc, out = run(prose)
check("prose mentioning 'Verdict' mid-sentence, as a heading and as a table cell "
      "does not match; only the marker line does",
      rc == 0 and out == f"Verdict: FIX-FIRST (the guard is untested) — head {SHA}",
      f"rc={rc} out={out!r}")

rc, out = run("Verdict at the end of this review, I promise.")
check("a sentence STARTING with the word Verdict but with no colon does not match",
      rc == 2, f"rc={rc} out={out!r}")

rc, out = run("### Verdict\n\nSome discussion but no marker line.")
check("a `### Verdict` heading alone does not match", rc == 2, f"rc={rc} out={out!r}")

# ---------------------------------------------------------------- arm 4
# Bold is NOT accepted, and that is a measured choice rather than strictness for
# its own sake. Over the same 150 comments, a bold marker is never the only
# marker (0 of 150), so accepting it rescues nothing -- while a bold PROSE
# sentence does occur (2 of 150: `**Verdict: this meets the merge bar.** ...`,
# PRs #4354 and #4291) directly above the real line. So tolerating bold turns
# two correctly-readable comments into two-marker refusals.
prose_bold = (
    "**Verdict: this meets the merge bar.** The fix is correct and proven.\n\n"
    f"Verdict: MERGE — head {SHA}{FOOTER}"
)
rc, out = run(prose_bold, "--field", "head")
check("a bold `**Verdict: ...**` PROSE sentence above the real line does not "
      "become a second marker (measured on PRs #4354 and #4291)",
      rc == 0 and out == SHA, f"rc={rc} out={out!r}")

rc, out = run(f"**Verdict:** MERGE — head {SHA}")
check("...so a bold-only marker does not match at all (0 of 150 comments rely on it)",
      rc == 2, f"rc={rc} out={out!r}")

rc, out = run(f"See the table: | x | Verdict: MERGE — head {SHA} |")
check("a marker NOT at start-of-line does not match",
      rc == 2, f"rc={rc} out={out!r}")

rc, out = run(f"  Verdict: MERGE — head {SHA}")
check("an INDENTED marker does not match: indentation is how markdown marks "
      "quoted content, so a quoted verdict must not read as one issued now",
      rc == 2, f"rc={rc} out={out!r}")

# ---------------------------------------------------------------- arm 5
# Malformed is a third state, distinct from both found and absent: a marker
# line whose head is not a full 40-char SHA cannot be used to check staleness,
# and saying "no verdict" about it would send the reader to the wrong remedy.
rc, out = run("Verdict: MERGE — head fd1ff0c8")
check("an abbreviated head SHA is MALFORMED (exit 3), not absent and not usable",
      rc == 3, f"rc={rc} out={out!r}")

rc, out = run(f"Verdict: SHIPIT — head {SHA}")
check("an unknown decision word is malformed (exit 3)", rc == 3, f"rc={rc} out={out!r}")

rc, out = run("Verdict: MERGE")
check("a marker line with no head at all is malformed (exit 3)",
      rc == 3, f"rc={rc} out={out!r}")

# ---------------------------------------------------------------- arm 6
# Two marker lines never occur in the measured population (0 of 150), so
# there is no established precedence rule to apply. Guessing one would make the
# tool silently pick a verdict nobody wrote.
rc, out = run(f"Verdict: FIX-FIRST (x) — head {SHA}\n\nVerdict: MERGE — head {SHA}")
check("two marker lines in one comment refuse (exit 3) rather than guessing which wins",
      rc == 3, f"rc={rc} out={out!r}")

# ---------------------------------------------------------------- arm 7
# FIX-FIRST and HOLD carry a reason; MERGE carries none. The arming step only
# arms on MERGE, so conflating them is the dangerous direction.
rc, out = run(f"Verdict: HOLD (no verdict yet) — head {SHA}", "--field", "decision")
check("HOLD is read as HOLD, not as MERGE", rc == 0 and out == "HOLD", f"rc={rc} out={out!r}")

rc, out = run(f"Verdict: FIX-FIRST (the test proves nothing) — head {SHA}", "--field", "reason")
check("a FIX-FIRST reason is recoverable", rc == 0 and out == "the test proves nothing",
      f"rc={rc} out={out!r}")

# CRLF: GitHub returns comment bodies with \r\n, and a \r left on the end of the
# SHA makes a string compare against `headRefOid` fail while looking identical.
rc, out = run(f"Looks good.\r\n\r\nVerdict: MERGE — head {SHA}\r\n\r\n---\r\n_Generated by [Claude Code](x)_",
              "--field", "head")
check("a CRLF body yields a head with no stray carriage return",
      rc == 0 and out == SHA, f"rc={rc} out={out!r}")

# ---------------------------------------------------------------- arm 7b
# "could not read anything" is a fourth state, not a malformed verdict and above
# all not exit 1: a verdict reader exiting 1 reads as "a verdict was found and
# it was negative", which is the shape `ci-verdicts.md` records for a `ci-wait.py`
# copy that hit a decode error and was taken for a failing required check.
def run_pr(*args: str, path: str | None = None) -> int:
    env = dict(os.environ)
    if path is not None:
        env["PATH"] = path
    return subprocess.run(
        [sys.executable, TOOL, "--pr", "999999", "--repo", "x/y", *args],
        capture_output=True, text=True, env=env,
    ).returncode


rc = run_pr(path="")  # no `gh` on PATH at all: every web and remote session
check("with no `gh` available, --pr exits 4 (unreadable), never 0, 2 or 1",
      rc == 4, f"rc={rc}")

# ---------------------------------------------------------------- arm 8
# The prose and the tool must not drift apart: the contract other loops follow
# is the prose, and nothing executes prose (#3955).
def read(path: str) -> str:
    with open(os.path.join(ROOT, path), encoding="utf-8") as fh:
        return fh.read()


reviewer = read(".claude/agents/reviewer.md")
skill = read(".claude/skills/orchestrating-a-session/SKILL.md")

check("reviewer.md no longer states the done-condition as the comment's LAST line",
      "posted comment's last line is the verdict line" not in reviewer,
      "the positional contract is still the stated done-condition")
check("the arming step no longer keys on a comment's last line",
      "whose last line begins `Verdict:`" not in skill,
      "the arming step still reads the last line")
check("reviewer.md names the marker as start-of-line",
      "start of a line" in reviewer or "start-of-line" in reviewer)
check("the arming step points at tools/review-verdict.py",
      "review-verdict.py" in skill)
check("reviewer.md points at tools/review-verdict.py",
      "review-verdict.py" in reviewer)

print("")
print(f"{passes} passed, {len(failures)} failed")
sys.exit(1 if failures else 0)
