#!/usr/bin/env python3
"""`tools/review-claim.py` must answer at START of a review, not at completion (#4284).

A PR at `status: review-ready` reads identically whether nobody is reviewing it
or three agents already are. `check-open-prs-before-claiming.md` gives three
signals for implementation ownership and none for review, so every sweeping
coordinator sees the same review-ready PR and dispatches at it.

WHAT THE ARMS ARE PINNING, and why a completion-time signal fails

Measured over the 60 most recent pull requests on 2026-09-19 (59 carry a
`Verdict:` comment), counting repeats on the IDENTICAL head, where nothing
about the PR changed and the second pass is redundant by construction:

    18 of 59 PRs (31%)  carry >=2 verdicts on one head -- 19 pairs
    17 of the 19 pairs  are under 15 minutes apart; median 5.5 min

A review takes ~15 minutes, so 17 of 19 second reviewers STARTED while the
first was still running. The `live claim with no verdict yet` arm below is the
one those 17 need, and it is exactly the arm a `status: reviewed` label written
at completion cannot serve -- which is why it is here and why the control
beside it matters.

THE CONTROL (`guards-need-a-third-state.md`)

A reporter that answered CLAIMED for everything would pass every refusal arm
above and be useless. `free: no claim, no verdict` and `free: stale claim only`
are the arms that fail if it starts over-reporting, and they are the reason a
refusal arm passing means anything at all.

Run directly: python3 tools/test_review_claim.py
"""
from __future__ import annotations

import datetime
import json
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOOL = os.path.join(ROOT, "tools", "review-claim.py")

HEAD = "4cfe233e5fb774fc53555b945f8819fca17c5939"
OTHER = "0a9897491505d5344a0f333e6ce4493b4baa4b52"
FOOTER = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"

FREE, CLAIMED, UNREADABLE = 0, 1, 3

failures: list[str] = []
passes = 0


def check(label: str, ok: bool, detail: str = "") -> None:
    global passes
    if ok:
        passes += 1
        print(f"PASS  {label}")
    else:
        failures.append(label)
        print(f"FAIL  {label}")
        if detail:
            for line in detail.strip().splitlines():
                print(f"        {line}")


def ago(minutes: float) -> str:
    when = (datetime.datetime.now(datetime.timezone.utc)
            - datetime.timedelta(minutes=minutes))
    return when.strftime("%Y-%m-%dT%H:%M:%SZ")


def comment(body: str, minutes: float = 1.0) -> dict:
    return {"body": body, "created_at": ago(minutes)}


def run(comments: list[dict], head: str = HEAD, extra: list[str] | None = None):
    return subprocess.run(
        [sys.executable, TOOL, "--pr", "4306", "--stdin", "--head", head]
        + (extra or []),
        input=json.dumps(comments), capture_output=True, text=True,
        encoding="utf-8", errors="replace")


# --- the control: it must say FREE when the PR genuinely is ------------------
# Without these two arms every refusal arm below is satisfied by a tool that
# answers CLAIMED unconditionally.

r = run([])
check("control: no comments at all reads FREE",
      r.returncode == FREE and "FREE" in r.stdout, r.stdout + r.stderr)

r = run([comment("Nice work, this looks reasonable to me."),
         comment("Rebased onto main.")])
check("control: ordinary comments carrying no marker read FREE",
      r.returncode == FREE, r.stdout + r.stderr)

r = run([comment(f"Reviewing: stma-auto-9 — head {OTHER}", minutes=3)])
check("control: a claim on a SUPERSEDED head does not hold",
      r.returncode == FREE and "stale" in r.stdout.lower(), r.stdout + r.stderr)

r = run([comment(f"Reviewing: stma-auto-9 — head {HEAD}", minutes=120)])
check("control: a claim older than --max-age does not hold (a dead reviewer "
      "must not lock a PR)",
      r.returncode == FREE and "expired" in r.stdout.lower(), r.stdout + r.stderr)

r = run([comment(f"Verdict: MERGE — head {OTHER}", minutes=30)])
check("control: a verdict on an OLDER head does not hold (the head moved, so a "
      "fresh pass is what should happen)",
      r.returncode == FREE, r.stdout + r.stderr)

# --- the signal: a review in flight ----------------------------------------
# The arm 17 of the 19 measured pairs needed, and the one no completion-time
# label can serve.

r = run([comment(f"Reviewing: stma-auto-9 — head {HEAD}", minutes=4)])
check("a LIVE claim with no verdict yet reads CLAIMED (the concurrent-start case)",
      r.returncode == CLAIMED and "LIVE" in r.stdout, r.stdout + r.stderr)

# The gap that actually occurred on #4306: 123 seconds.
r = run([comment(f"Reviewing: stma-auto-9 — head {HEAD}", minutes=2.05)])
check("a claim 2.05 min old reads CLAIMED (#4306's real gap was 123s)",
      r.returncode == CLAIMED, r.stdout + r.stderr)

# --- the signal: already reviewed at this exact head -----------------------

r = run([comment(f"Verdict: MERGE — head {HEAD}", minutes=8)])
check("a verdict on THIS head reads CLAIMED",
      r.returncode == CLAIMED and "THIS-HEAD" in r.stdout, r.stdout + r.stderr)

r = run([comment(f"Verdict: FIX-FIRST (no mutation) — head {HEAD}", minutes=8)])
check("a FIX-FIRST verdict on this head reads CLAIMED too -- the question is "
      "whether a pass happened, not what it concluded",
      r.returncode == CLAIMED, r.stdout + r.stderr)

# --- a finished claim is not a second live reviewer -------------------------
# Both markers from one pass must not read as two reviewers, or every completed
# review makes its own PR look contended.

r = run([comment(f"Reviewing: stma-auto-9 — head {HEAD}", minutes=20),
         comment(f"Verdict: MERGE — head {HEAD}", minutes=5)])
check("a claim whose verdict has landed reads DONE, not LIVE",
      r.returncode == CLAIMED and "[DONE]" in r.stdout and "[LIVE]" not in r.stdout,
      r.stdout + r.stderr)

# --- marker discipline, inherited from review-verdict.py -------------------

r = run([comment(f"Reviewing: stma-auto-9 — head {HEAD}" + FOOTER, minutes=4)])
check("an attribution footer below the claim does not hide it (#4338's shape)",
      r.returncode == CLAIMED, r.stdout + r.stderr)

r = run([comment(f"  Reviewing: stma-auto-9 — head {HEAD}", minutes=4)])
check("an INDENTED claim is quoted content, not a claim issued now",
      r.returncode == FREE, r.stdout + r.stderr)

r = run([comment(f"**Reviewing:** stma-auto-9 — head {HEAD}", minutes=4)])
check("a bold marker is not a claim (same anchor as review-verdict.py)",
      r.returncode == FREE, r.stdout + r.stderr)

r = run([comment(f"Reviewing: stma-auto-9 — head {HEAD[:8]}", minutes=4)])
check("an abbreviated head cannot be compared, so it holds nothing",
      r.returncode == FREE, r.stdout + r.stderr)

r = run([comment("I am reviewing this now, head looks fine", minutes=4)])
check("prose containing the word does not claim the PR",
      r.returncode == FREE, r.stdout + r.stderr)

# --- the third state --------------------------------------------------------

r = run([], extra=[])
proc = subprocess.run(
    [sys.executable, TOOL, "--pr", "4306", "--stdin", "--head", HEAD],
    input="{not json", capture_output=True, text=True)
check("unparseable comments read UNREADABLE, never FREE",
      proc.returncode == UNREADABLE, proc.stdout + proc.stderr)

proc = subprocess.run([sys.executable, TOOL, "--pr", "4306", "--stdin"],
                      input="[]", capture_output=True, text=True)
check("--stdin without --head is refused rather than judged against nothing",
      proc.returncode not in (FREE, CLAIMED), proc.stdout + proc.stderr)

proc = subprocess.run([sys.executable, TOOL, "--pr", "4306", "--post"],
                      capture_output=True, text=True)
check("--post without --agent-id is refused: an unattributable claim holds nothing",
      proc.returncode not in (FREE, CLAIMED), proc.stdout + proc.stderr)

# --- it reports, it never blocks -------------------------------------------
# The issue is explicit that a second pass is sometimes right (#4281's fourth
# pass found what three did not). A tool that could refuse would be the wrong
# remedy, so pin that there is no flag to route around.

# Ask argparse, not the text. The docstring explains WHY there is no --force,
# so a substring test over the source finds that sentence and reads its own
# rationale as the defect -- which is exactly what it did when first written.
proc = subprocess.run([sys.executable, TOOL, "--pr", "4306", "--stdin",
                       "--head", HEAD, "--force"],
                      input="[]", capture_output=True, text=True)
check("the tool accepts no --force: it reports rather than blocks, so there is "
      "nothing to route around",
      proc.returncode not in (FREE, CLAIMED)
      and "unrecognized arguments" in (proc.stdout + proc.stderr),
      proc.stdout + proc.stderr)

print()
print(f"{passes} passed, {len(failures)} failed")
if failures:
    for f in failures:
        print(f"  FAILED: {f}")
sys.exit(1 if failures else 0)
